### PR TITLE
Add CMake tests from a test list

### PR DESCRIPTION
**Pull request by pyohannes**
A suggestion to reduce copy/paste efforts when maintaining the CMake files.

### CODE REVIEW

**Comment by rnburn** [comment]
@paivagustavo - is this good to merge?

**Comment by paivagustavo** [comment]
@rnburn I think you tagged me by mistake, I'm approver on the Go Sig :)

**Comment by pyohannes** [comment]
@rnburn I think it's good to merge. I have no permissions to do so though.

**Comment by rnburn** [comment]
Ok - I'll merge it.

Sorry for the @ing mixup.

**Pull request merged**
