### PR TITLE
Add a Timestamp type

### PR DESCRIPTION
**Pull request by rnburn**

### CODE REVIEW

**Comment by g-easy** [comment]
Q1. From a data model point of view: if we're going to have a concrete Timestamp object, what should it look like?

e.g. StackDriver exporter uses protobuf standard Timestamp message which is basically the same as `struct timespec` which `clock_gettime` uses. All of these look like:
```
int64_t seconds;
uint64_t nanos;
```

(absl::Time is similar except quarter-nanos because someone wanted to squeeze out two additional bits of precision)

I have some concerns about:
* Using a single int64 (although this looks like what otel-java does [link](https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/trace/EndSpanOptions.java#L74))
* Baking in the requirement for two clocks.

Q2. I'm also not convinced we should mandate the use of a monotonic clock for anything. It's much slower to read (on Linux x86, reading the monotonic clock is a syscall while getting system time is just a memory read) and the system clock almost never steps backwards (leap seconds, and ntpdate during boot). Is it worth paying the syscall tax on every Span even though almost no Spans will be affected by this?

My proposal: make `opentelemetry::Timestamp` look like `struct timespec` and let the user and/or sdk make decisions about which clocks to use for timestamps.

**Comment by rnburn** [comment]
> Baking in the requirement for two clocks.
This allows for two timestamp, but doesn't require two timestamps -- you can leave leave one of them unset.

**Comment by g-easy** [comment]
> you can leave one of them unset

That's fair. But what about making Timestamp an absolute time and letting the user/sdk worry about conversions between clocks? That way I could use e.g. TSC instead of the C++11 "steady" clock, for monotonic time.

**Comment by rnburn** [comment]
> My proposal: make opentelemetry::Timestamp look like struct timespec and let the user and/or sdk make decisions about which clocks to use for timestamps.

You need to know which epoch the timestamp refers to. If a user specifies an explicit start timestamp, but doesn't specify a finish timestamp, then the SDK needs to provide the finish timestamp and the delta wouldn't make any sense unless it refers to the same epoch as the user-provided timestamp.

**Comment by g-easy** [comment]
Right. My proposal is to use the Unix epoch like `timespec` and friends. If the user wants to specify a custom start time, it's up to them to convert whatever time they read to Unix epoch time. I'm guessing all the exporters need it in this epoch also.

**Comment by rnburn** [comment]
> Right. My proposal is to use the Unix epoch like timespec and friends. If the user wants to specify a custom start time, it's up to them to convert whatever time they read to Unix epoch time. I'm guessing all the exporters need it in this epoch also.

You lose the benefits of the monotonic clock if you do that, as it's more accurate for measuring durations. Some issues around preferring monotonic to system for this type of timing
https://github.com/Netflix/rend/issues/96
https://github.com/lightstep/lightstep-tracer-cpp/issues/47

**Comment by rnburn** [comment]
> My proposal is to use the Unix epoch like timespec and friends.

timespec doesn't specify the epoch (it's just a duration type). If you call clock_gettime for the system clock, it will use the Unix Epoch; if you use the monotonic clock id, it's measuring from an unspecified epoch (usually something like when the OS was last booted).

**Comment by g-easy** [comment]
> You lose the benefits of the monotonic clock

When displaying an end time or an annotation time as an absolute time, you would use start time + interval, right? How does this lose the benefits of the monotonic clock?

Basically what I'm pushing for is for opentelemetry to not be in the epoch conversion business. :)

> timespec doesn't specify the epoch

You're right, I mis-spoke. But in terms of the data model, and what needs to end up in exporters, we will have some mix of absolute timestamps, all of which I assume will be Unix epoch, and intervals. I think this is orthogonal to the question of which clocks are read when, and I'd like to keep the API both simple and unrestrictive.

**Comment by rnburn** [comment]
> When displaying an end time or an annotation time as an absolute time, you would use start time + interval, right? How does this lose the benefits of the monotonic clock?

The benefits of the monotonic clock are for measuring the interval. You want
```
interval = monontic_finish - mononic_start
```
I should be able to do something like this

```
auto timepoint = {system_clock::now(), mononotic_clock::now()};
// ...
span = start_span("abc", start_time=timepoint);
span->finish();
```
The SDK can compute interval by taking the monotonic timestamp and diffing with the start monotonic time.

... But in your proposal, the user would have to convert timepoint to be measured off of the unix epoch first doing something like this https://stackoverflow.com/questions/35282308/convert-between-c11-clocks/35282833#35282833 -- that loses the benefits of monotonic clocks for computing the interval.

**Comment by g-easy** [comment]
Right. So should the tracer be in the interval business, or the caller? e.g.:

```
t0 = Now();
mono0 = MonoNow();
span = StartSpan(t0);
...
span.AddAnnotation("Did work.", t0 + MonoNow() - mono0);
```

The above is wordy, but only applies to users who really care about it. By default, instrumentation can just use system time:

```
span = StartSpan();
span.AddAnnotation("Did work.");
```

Or do we actually want to force all instrumentation to use the monotonic clock all the time?

My concerns are:
* Monotonic clock is slow to read.
* It doesn't protect us from clock frequency being wrong.
* It doesn't protect us from clock offset being wrong.
* Leap seconds are going to cause problems regardless.

Monotonic time really only helps with time moving backwards, which happens rarely:
* Operator moving time backwards on a running system with `date(1)`.
* ntpd moving time backwards during boot.
* Leap seconds, by POSIX definition, replay time. (in this case you can capture intervals correctly but not absolute times so your traces will be weird regardless)

I don't think it's worth paying for the runtime or cognitive overhead of using two clocks.

I think discrepancies between multiple computers (in the distributed tracing case) are going to come up way more often than the issue of time going backwards.

**Comment by rnburn** [comment]
> Right. So should the tracer be in the interval business, or the caller? e.g.:

Of course tracers are in the interval business. They track the interval for span. Having the user provide the span interval would be a major departure for the opentelemetry api.

> Monotonic time really only helps with time moving backwards, 

Why does it only help with time moving backwards. NTP can adjust the system clock either forwards or backwards.

> CLOCK_REALTIME is affected by NTP, and can move forwards and backwards. CLOCK_MONOTONIC is not, and advances at one tick per tick.

https://stackoverflow.com/a/3523482/4447365

> which happens rarely:
> * ntpd moving time backwards during boot.

I'm not following: NTPD continually adjusts the system clock according to the polling interval. It doesn't happen just at boot time.

> minpoll minpoll
> 
> maxpoll maxpoll
> 
> These options specify the minimum and maximum poll intervals for NTP messages, in seconds as a power of two. The maximum poll interval defaults to 10 (1,024 s), but can be increased by the maxpoll option to an upper limit of 17 (36.4 h). The minimum poll interval defaults to 6 (64 s), but can be decreased by the minpoll option to a lower limit of 3 (8 s). These option are valid only with the server and peer commands.

https://askubuntu.com/a/798032

**Comment by rnburn** [comment]
And btw, this mattered enough for Envoy to switch to use monotonic clocks for intervals
https://github.com/envoyproxy/envoy/issues/312

**Comment by g-easy** [comment]
> Having the user provide the span interval would be a major departure for the opentelemetry api

What about providing custom timestamps, like in my earlier snippet?

> NTPD continually adjusts the system clock

ntpd continually adjusts the clock *frequency*, which they call "slew." It works hard not to "step" the time discontinuously.

`CLOCK_MONOTONIC` *is* affected by frequency changes. `CLOCK_MONOTONIC_RAW` is not - but that probably makes it less accurate.

> Envoy

What motivated this? I can imagine situations where moving time backwards causes an interval timer to misbehave in a way that affects correctness. I'm less worried about a timestamp in a trace being very occasionally wrong.

**Comment by rnburn** [comment]
> t0 = Now();
mono0 = MonoNow();
span = StartSpan(t0);
...
span.AddAnnotation("Did work.", t0 + MonoNow() - mono0);

I don't know what you're doing here. Timestamps aren't specified with AddAnnotation. You can optionally specify timestamps with StartSpan, AddEvent, and FinishSpan (look at the [Python API](https://github.com/open-telemetry/opentelemetry-python/blob/master/opentelemetry-api/src/opentelemetry/trace/__init__.py)). If you do specify them just do something like this
```
auto t = std::chrono::steady_clock::now();
span.AddEvent("abc"); // no timestamp, tracer stamps the time for you
span.AddEvent("abc", t); // specify a timestamp.
```

You only use the two timestamps from the different clocks when you start the span. And stamping from two clocks so that you can use monotonic timestamps for interval measurements is the same thing the Go language does https://golang.org/pkg/time/#hdr-Monotonic_Clocks

**Comment by g-easy** [comment]
> Timestamps aren't specified with AddAnnotation

Fair enough, although I feel like that ought to be possible. :)

(I thought annotations had timestamps and attributes didn't)

> You only use the two timestamps from the different clocks when you start the span

```
t0 = SystemNow();
t1 = MonoNow();
StartSpan(t0, t1);
// Time steps here.
t2 = MonoNow();
EndSpan(t2);
```

With the above, the length of the span will be correct but both the start and end times will be wrong, no?

**Comment by g-easy** [comment]
I'm trying to understand what problem we're trying to solve. Is it worth having accurate intervals given:
 * Usually the absolute times will be correct.
 * When they're incorrect, is there value in having correct intervals?

Also I ran some benchmarks and the numbers are a little bit different than I expected:

```
---------------------------------------------------------------
Benchmark                     Time             CPU   Iterations
---------------------------------------------------------------
BM_System                  14.5 ns         14.5 ns     41608841 (std::chrono::system_clock::now)
BM_Steady                  14.1 ns         14.1 ns     49467610 (std::chrono::steady_clock::now)
BM_Time                    1.69 ns         1.69 ns    408922356 (time(NULL) - only accurate to 1 sec)
BM_GetTimeMono             13.5 ns         13.5 ns     50805617 (clock_gettime)
BM_GetTimeMonoRaw           466 ns          466 ns      1548030 (lmao what)
BM_GetTimeMonoCoarse       3.91 ns         3.91 ns    170583040 (only accurate to 4msec)
BM_GetTimeCoarse           3.22 ns         3.22 ns    217001807
BM_AbslNow                 6.64 ns         6.64 ns    105592715
```

My take-aways are:
* I don't think we want to use `CLOCK_*_COARSE` because it's too coarse.
* System and steady take the same amount of time.
* C++11 chrono and clock_gettime take the same amount of time.

**Comment by tigrannajaryan** [comment]
> Q1. From a data model point of view: if we're going to have a concrete Timestamp object, what should it look like?
> 
> e.g. StackDriver exporter uses protobuf standard Timestamp message which is basically the same as `struct timespec` which `clock_gettime` uses. All of these look like:
> 
> ```
> int64_t seconds;
> uint32_t nanos;  // edit: I incorrectly wrote 64 here at first
> ```
> 
> (absl::Time is similar except quarter-nanos because someone wanted to squeeze out two additional bits of precision)
> 
> I have some concerns about:
> 
>     * Using a single int64 (although this looks like what otel-java does: [link](https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/trace/EndSpanOptions.java#L74))
> 

For reference OTLP uses int64 nanoseconds since Unix epoch: https://github.com/open-telemetry/opentelemetry-proto/blob/839beca3755237c22fb950ae4ca5e1305dd85015/opentelemetry/proto/trace/v1/trace.proto#L121

**Comment by g-easy** [comment]
Thanks Tigran! If that's what's in the proto, I withdraw my concern about using a single int64.

`fixed` is unsigned BTW. Ryan, do you think we should change int64_t micros to uint64_t nanos to match the proto?

uintmax64 nanos is good enough until the year 2554.

**Comment by tigrannajaryan** [comment]
> Thanks Tigran! If that's what's in the proto, I withdraw my concern about using a single int64.
> 
> `fixed` is unsigned BTW.
Yes, my mistake, it's uint64. We played a bit with the timestamps, it was sfixed64 initially.

**Comment by rnburn** [comment]
> t0 = SystemNow();
t1 = MonoNow();
StartSpan(t0, t1);
// Time steps here.
t2 = MonoNow();
EndSpan(t2);
With the above, the length of the span will be correct but both the start and end times will be wrong, no?

Assuming the step was to correct the system clock, yes.

> I'm trying to understand what problem we're trying to solve. Is it worth having accurate intervals given:

> Usually the absolute times will be correct.
> When they're incorrect, is there value in having correct intervals?

Suppose I query a tracing system to look at all spans for an operation with outlier durations. Then I'd like the duration measurement to be accurate so that I know I'm not looking at spans that are outliers because of clock adjustments.

Sure, the clock adjustments won't happen often, but the true outliers won't happen often either (by definition)

**Comment by rnburn** [comment]
> fixed is unsigned BTW. Ryan, do you think we should change int64_t micros to uint64_t nanos to match the proto?

Updated to uint64_t nanos

**Comment by g-easy** [comment]
> nanos

Nice. :)

> query by duration

That's a good point.

I have two suggestions:

1. What about if we split Timestamp into separate classes for Absolute vs Monotonic timestamps? That way we don't have to read two clocks each time, and it becomes clear from the type system which one needs to be used when.

e.g. default StartSpan would read both, and StartSpanOptions would require both, whereas AddEvent would take an optional Monotonic timestamp.

2. How can I in the resulting binary or in a custom SDK use something other than `chrono`? Can we make Timestamp(s) in the API just a typesafe wrapper around `uint64_t` and leave the implementation up to the SDK? e.g. `NoopTracer` in the API gets a `NoopClock`, default SDK uses `chrono`, and my custom SDK is free to use e.g. `absl::Now`.

What do you folks think?

**Comment by rnburn** [comment]
I split out into separate system and steady types.

I used an int64_t internally to hold the nanosecond count since [std::chrono::duration](https://en.cppreference.com/w/cpp/chrono/duration) requires a signed type and it didn't make much sense to use a unsigned int if it has to be cast back to a signed int anyways.

**Comment by g-easy** [comment]
int64_t still gets us to the year 2262. ;)

Thanks Ryan. Sorry for the long review.

**Pull request merged**
