### PR TITLE
Fix view names in Prometheus example

### PR DESCRIPTION
**Pull request by tyler92**
As far as I can see View should have the same name as Instrument

> The name of the View (optional). If not provided, the **Instrument name** MUST be used by default. This will be used as the name of the [metrics stream](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#events--data-stream--timeseries).

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#view

### CODE REVIEW

**Comment by tyler92** [comment]
I am a newcomer in OpenTelemetry so please let me know if I am wrong and if there is no error in the examples. Without this change I don't see "_counter" on the Prometheus page.

**Review by lalitb — APPROVED** [review]
Changes look good. Thanks for the contribution.

**Comment by tyler92** [comment]
If the change is good, I will change also README with pictures. And revome WIP after that. Right now I wanted to make sure that the fix is correct

**Comment by tyler92** [comment]
Why don't I see a picture like in README? I see lines instead of histograms. Where is a mistake?

image

**Comment by lalitb** [comment]
@tyler92   In case you are seeing a separate line for histogram bucket, the output is correct. The existing screenshot in README.md is from the previous implementation (prior to design changes in #1953), and is no longer valid output.

**Pull request merged**
