### PR TITLE
Upgrade to opentelemetry-proto 1.5.0

### PR DESCRIPTION
**Pull request by marcalff**
Contributes to #3201

## Changes

Please provide a brief description of the changes here.

* Upgrade to opentelemetry-proto 1.5.0

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by marcalff** [comment]
@keith Please add a build for opentelemetry-proto 1.5.0 in bazel central.

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/3445

**Comment by marcalff** [comment]
Do not merge:

CI will fail for bazel, until the bazel central repository PR is merged.

**Review by lalitb — APPROVED** [review]

**Comment by marcalff** [comment]
> Shouldn't https://github.com/open-telemetry/opentelemetry-cpp/blob/main/third_party_release have been updated too? If it should, I can open a PR.

@santigimeno Yes, thanks for spotting this.

PR welcome.

**Pull request merged**
