### PR TITLE
Fix some C++ warnings

### PR DESCRIPTION
**Pull request by quentingodeau**
## Changes

Fix API unused/reorder C++ warning that where propagate to others
on inclusion.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by lalitb — APPROVED** [review]
Thank you for fixing it. You have to sign the the CLA via EasyCLA before it can be merged ( as the easyCLA check is failing and blocking the merge).

**Review by reyang — APPROVED** [review]
LGTM.

**Review by ThomsonTan — APPROVED** [review]

**Comment by quentingodeau** [comment]
Hi thanks for the quick review. sorry for the force push but I finally found what was wrong with the EasyCLA issue it was my .gitconfig configuration I put the wrong noreply address, sorry for that...

**Comment by lalitb** [comment]
> Hi thanks for the quick review. sorry for the force push but I finally found what was wrong with the EasyCLA issue it was my .gitconfig configuration I put the wrong noreply address, sorry for that...

No issues. Thanks for your contribution. Will merge it now.

**Pull request merged**
