### PR TITLE
[WIP] Add security scanner CodeQL as part of CI

### LINKED ISSUE #652: Set up CodeQL GitHub action for OpenTelemetry C++ SDK repo
CodeQL is a security scanner: https://securitylab.github.com/tools/codeql/

It's very easy to set up: https://codeql.github.com/docs/

We should do it.

### PR DESCRIPTION
**Pull request by maxgolov**
Set up CodeQL GitHub action. No code changes. Additional code security scanner only.

Fixes #652

### CODE REVIEW

**Comment by maxgolov** [comment]
Need to setup prerequisites before running the build..

**Comment by lalitb** [comment]
Thanks for working on it. I did try it some time back, but CodeQL was somehow not able to identify the build system we are using.

**Comment by maxgolov** [comment]
> CodeQL was somehow not able to identify the build system we are using.

It's only dependency setup that needs fixing before running the CMake build. I'll fix it.

**Comment by ThomsonTan** [comment]
@maxgolov @lalitb could this be fixed as it is covered by PR https://github.com/open-telemetry/opentelemetry-cpp/pull/770 which was merged?

**Pull request closed without merging**
