### PR TITLE
[Exporter] add fix for prometheus exporter build

### PR DESCRIPTION
**Pull request by rgc183**
Fixes [# (issue)](https://github.com/open-telemetry/opentelemetry-cpp/issues/1728)

For prometheus exporter, required dependencies  are not loaded in repository.bzl. When Opentelemetry is imported in some other project, these dependencies are missing.

### CODE REVIEW

**Comment by lalitb** [comment]
@rgc183 Thanks for the fix. You would need to sign the CLA before you can contribute. Also, need to fix the code format as described here - https://github.com/open-telemetry/opentelemetry-cpp/blob/main/CONTRIBUTING.md#how-to-send-pull-requests

**Comment by marcalff** [comment]
@rgc183 Thanks for the fix.

Please fix the clang-format (extra line), see from the build logs:

```
diff --git a/bazel/extra_deps.bzl b/bazel/extra_deps.bzl
index 1c1ddda..5b892e5 100644
--- a/bazel/extra_deps.bzl
+++ b/bazel/extra_deps.bzl
@@ -3,7 +3,6 @@ load("@com_github_jupp0r_prometheus_cpp//bazel:repositories.bzl", "prometheus_cp
 load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
 load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")
 
-
 def opentelemetry_extra_deps():
     prometheus_cpp_repositories()
     bazel_skylib_workspace()
```

And please sign the CLA.

**Comment by lalitb** [comment]
@rgc183  - let us know if you need help with formatting, or have issues with CLA signing?

**Comment by rgc183** [comment]
@lalitb Please give me sometime, I am working with my organization to get CLA approval and some sign-offs.

**Review by owent — APPROVED** [review]
LGTM after CLA signed,

**Comment by rgc183** [comment]
@lalitb As a corporate contributor, when I select my organization, there is list of people I see as CLA managers. I do not see how to add new person to send an email to. Also, the person mentioned in the list, I cannot locate him internally.

**Comment by rgc183** [comment]
Created another MR: https://github.com/open-telemetry/opentelemetry-cpp/pull/1795 from my corporate account. Closing this one.

**Pull request closed without merging**
