### PR TITLE
Context Propagation Update: Headers

### PR DESCRIPTION
**Pull request by Tianlin-Zhao**
This branch contains the header file for httptextformat, an interface.

### CODE REVIEW

**Comment by Tianlin-Zhao** [comment]
There's a Bazel-related error:
`ERROR:The project you're trying to build requires Bazel 3.2.0 (specified in /Users/runner/runners/2.263.0/work/opentelemetry-cpp/opentelemetry-cpp/.bazelversion), but it wasn't found in /usr/local/Cellar/bazel/3.3.0/libexec/bin.`
I don't know if that's my coding's issue or just the setup of my laptop's.

**Comment by Tianlin-Zhao** [comment]
Also, there's a problem with span: there's a span.h under nostd folder and a span.h under trace folder. I am not sure which one I am supposed to be following with to define my functions.

**Comment by nadiaciobanu** [comment]
Is there any plan to merge this PR soon?

**Comment by Tianlin-Zhao** [comment]
> Is there any plan to merge this PR soon?

This is an old PR that I should have removed some time ago. Sorry for this confusion, please refer to https://github.com/open-telemetry/opentelemetry-cpp/pull/143 for my latest work.

**Comment by nadiaciobanu** [comment]
Okay, thanks! In that case you could close this PR.

**Pull request closed without merging**
