### PR TITLE
Fix build with clang 19

### PR DESCRIPTION
**Pull request by osokin**
Please see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281359 for details.

Credit:	Dimitry Andric <dim@FreeBSD.org>

Fixes # (issue)

## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by marcalff — APPROVED** [review]
Thanks for the fix.

LGTM once CLA is signed.

**Comment by osokin** [comment]
> Thanks for the fix.
> 
> LGTM once CLA is signed.

Signing the CLA requests mailing address, don't think I want to share it until I get details about CRUD for such data.

**Comment by lalitb** [comment]
> Signing the CLA requests mailing address, don't think I want to share it until I get details about CRUD for such data.

As you're signing the CLA for CNCF, which is part of the Linux Foundation, the collection and use of the email is governed by the Linux Foundation's privacy policy. You can review the details of their policy here: https://www.linuxfoundation.org/legal/privacy-policy.

**Review by lalitb — APPROVED** [review]
LGTM once CLA is signed.

**Review by owent — APPROVED** [review]

**Review by ThomsonTan — APPROVED** [review]

**Comment by marcalff** [comment]
Hi @osokin, have you made a decision regarding the Linux Foundation Contributor License Agreement (CLA) ?

Please indicate if this PR should be kept opened (to allow time to process the CLA), or if it should be closed.

Thanks.

**Comment by osokin** [comment]
> Hi @osokin, have you made a decision regarding the Linux Foundation Contributor License Agreement (CLA) ?
> 
> Please indicate if this PR should be kept opened (to allow time to process the CLA), or if it should be closed.
> 
> Thanks.

I decided not to sharing my mail address, sorry about that.

**Pull request closed without merging**
