### PR TITLE
Moved otlp_grpc_utils.cc to opentelemetry_exporter_otlp_grpc_client.

### LINKED ISSUE #1826: [Build] Build break when using WITH_OTLP_HTTP=ON, WITH_OTLP_GRPC=OFF
When compiling with the OTLP HTTP exporter but *not* the OTLP GRPC exporter,
the build fails:

```
In file included from .../opentelemetry-cpp/opentelemetry-cpp-1.8.0/exporters/otlp/src/otlp_grpc_utils.cc:4:
.../opentelemetry-cpp/opentelemetry-cpp-1.8.0/exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_utils.h:6:10: fatal error: grpcpp/grpcpp.h: No such file or directory
    6 | #include <grpcpp/grpcpp.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

Suggested fix for `exporter/otlp/CMakeLists.txt`:

- do not add `otlp_grpc_utils.cc` in the `opentelemetry_otlp_recordable` library
- add `otlp_grpc_utils.cc` in the `opentelemetry_exporter_otlp_grpc` library instead ? (to investigate)

### PR DESCRIPTION
**Pull request by lalitb**
Fixes #1826

## Changes

Moved otlp_grpc_utils.cc to opentelemetry_exporter_otlp_grpc_client.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by esigo** [comment]
Shall we make this consistent with our bazel?
https://github.com/open-telemetry/opentelemetry-cpp/blob/82d8cb49cdc2104ef5db1f73cf362a6c7a8a76a2/exporters/otlp/BUILD#L50-L64

**Comment by lalitb** [comment]
> 

Yes, good point to be consistent with bazel. Will do so

**Comment by lalitb** [comment]
Or should we have single library otlp_grpc_client for both bazel and cmake, as in the latest changes in this PR - I don't see reason to have two different libraries for gRPC stuff.

**Comment by esigo** [comment]
> Or should we have single library otlp_grpc_client for both bazel and cmake, as in the latest changes in this PR - I don't see reason to have two different libraries for gRPC stuff.

Yeah agree. doesn't make sense to have two libs.

**Comment by ThomsonTan** [comment]
> > Or should we have single library otlp_grpc_client for both bazel and cmake, as in the latest changes in this PR - I don't see reason to have two different libraries for gRPC stuff.
> 
> Yeah agree. doesn't make sense to have two libs.

+1. Put all grpc specific code in otlp_grpc_client makes sense for both bazel and cmake.

**Review by marcalff — APPROVED** [review]
Thanks for the fix

**Review by esigo — APPROVED** [review]
LGTM
Thanks for the fix :)

**Pull request merged**
