### PR TITLE
Fix SpinLockMutex for intel compilers

### LINKED ISSUE #1771: [API common] undefined reference to __builtin_ia32_pause when using Intel Compilers
**Describe your environment** 
C Compiler : icc version 19.0.3.199 (gcc version 9.3.1 compatibility)
C++ Compiler : icpc version 19.0.3.199 (gcc version 9.3.1 compatibility)

I am getting an undefined reference to `__builtin_ia32_pause` from common::SpinLockMutex.

It seems that the Intel C++ compiler can't link the GCC built-in function `__builtin_ia32_pause`.

### PR DESCRIPTION
**Pull request by gabswb**
Fixes #1771 

## Changes

see intel Pause Intrinsic [doc](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/intrinsics/intrinsics-for-sse2/miscellaneous-functions-and-intrinsics/pause-intrinsic.html)

Include `immintrin.h` and use `_mm_pause()` when `__INTEL_COMPILER` defined.
Could also use `sched_yield()` from `sched.h` but the solution above seems to work.

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by lalitb — APPROVED** [review]
Looks good, if this has been tested on Intel compiler. Please fix the format as given [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/CONTRIBUTING.md#how-to-send-pull-requests), and CLA.

**Review by marcalff — APPROVED** [review]

**Review by owent — APPROVED** [review]

**Comment by gabswb** [comment]
Yes, that's what I thought... I had clang-format v15.
I tried clang-format 10.0.0 from pip. If it is still not good, I should do it manually.

Thanks

**Review by ThomsonTan — APPROVED** [review]

**Comment by ThomsonTan** [comment]
> I'm just waiting for my company's approval to sign the CLA

@gabswb how is this going?

**Comment by gabswb** [comment]
> @gabswb how is this going?

The CLA should be signed now

**Comment by gabswb** [comment]
Is it good for you ?

**Comment by lalitb** [comment]
> Is it good for you ?

@gabswb looks like CLA is still missing, and the CI is failing for it.

**Pull request closed without merging**
