### PR TITLE
[BUILD] Fix multiple assignment operators for SpinLockMutex

### LINKED ISSUE #2500: Warning: Multiple assignment operators specified for SpinLockMutex
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.

Issue exists in the main branch too, when building we see this warning pop up on using otlp metrics related code;
```
17>c:\work\ic3\d_nsshe_lcsminedgetmp\en-us\amd64chk\packages\opentelemetry.cpp.geneva.1.0.2300\api\include\opentelemetry\common\spin_lock_mutex.h(132) : error C4522: 'opentelemetry::v1::common::SpinLockMutex': multiple assignment operators specified
```

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.
Build with this sample code:
```
#include "opentelemetry/exporters/etw/etw_tracer_exporter.h"
#include "opentelemetry/exporters/otlp/otlp_grpc_metric_exporter_factory.h"
#include "opentelemetry/metrics/provider.h"
#include "opentelemetry/sdk/metrics/export/periodic_exporting_metric_reader.h"
#include "opentelemetry/sdk/metrics/meter.h"
#include "opentelemetry/sdk/metrics/meter_provider.h"

using namespace OPENTELEMETRY_NAMESPACE;
using namespace opentelemetry::exporter::etw;
namespace otlp_exporter = opentelemetry::exporter::otlp;
namespace metrics_sdk = opentelemetry::sdk::metrics;
namespace metrics_api = opentelemetry::metrics;
namespace resource_ns = opentelemetry::sdk::resource;

    void InitOTelMetrics() 
    {
        // Initialize exporter
        otlp_exporter::OtlpGrpcMetricExporterOptions options;
        options.aggregation_temporality = static_cast<opentelemetry::v1::exporter::otlp::PreferredAggregationTemporality>(opentelemetry::v1::sdk::metrics::AggregationTemporality::kDelta);
        options.endpoint = "http://localhost:4317";
        auto exporter = otlp_exporter::OtlpGrpcMetricExporterFactory::Create(options);

        // Initialize metric reader
        metrics_sdk::PeriodicExportingMetricReaderOptions reader_options;
        reader_options.export_interval_millis = std::chrono::milliseconds(60 * 1000); // 1 min
        reader_options.export_timeout_millis  = std::chrono::milliseconds(500);
        std::unique_ptr<metrics_sdk::MetricReader> reader{
            new metrics_sdk::PeriodicExportingMetricReader(std::move(exporter), reader_options)};

        // Initialize MeterProvider
        resource_ns::ResourceAttributes attributes = {
            {"service", ServiceName}, {"_microsoft_metrics_account", "account"}, {"_microsoft_metrics_namespace", "counter"}
        };
        auto resource = resource_ns::Resource::Create(attributes);
        auto views = std::unique_ptr<metrics_sdk::ViewRegistry>(new metrics_sdk::ViewRegistry());
        auto provider = std::shared_ptr<metrics_api::MeterProvider>(new metrics_sdk::MeterProvider(std::move(views), resource));
        auto p = std::static_pointer_cast<metrics_sdk::MeterProvider>(provider);
        p->AddMetricReader(std::move(reader));
        metrics_api::Provider::SetMeterProvider(provider);
    }
```

**What is the expected behavior?**
No such warning is thrown

**What is the actual behavior?**
Warning C4522 is thrown.

**Additional context**

### PR DESCRIPTION
**Pull request by SaiHarshaK**
Fixes #2500 

## Changes

Please provide a brief description of the changes here.
The multiple assignment operators for SpinLockMutex throws warnings in consumer build for these headers. This would require them to explicitly add #Pragma to ignore C4522.

This PR removes the redundant assignment to let the build pass without these warnings. Tested locally as I was able to repro this issue before this change.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by marcalff — COMMENTED** [review]
Thanks for the quick PR.

I would rather remove the volatile declaration instead,
and keep the regular one.

**Comment by SaiHarshaK** [comment]
@marcalff I wasn't sure if there was any specific use case around why volatile was added in the first place, so assumed that might be the safer one to add.
I can certainly update this PR to use the other one.

**Comment by ThomsonTan** [comment]
Both declarations are marking the assignment operator as deleted instead of defining it. I am still not quite sure the reason of the triggered warning.

**Comment by SaiHarshaK** [comment]
Had to repush for clearing EasyCLA

**Review by marcalff — APPROVED** [review]
LGTM, thanks for the fix.

**Comment by ThomsonTan** [comment]
I didn't repro the warning with MSVC 19.38.33134, and also both overloads look correct to me, so could it be an issue for the specific MSVC @SaiHarshaK is using?

**Comment by SaiHarshaK** [comment]
Perhaps so, I don't have a way to currently update and check the same, since the infra on which build runs is out of my control.

**Review by owent — APPROVED** [review]

**Pull request merged**
