### PR TITLE
[BUILD] 'uint8_t' not declared in this scope with gcc 13.2.1

### PR DESCRIPTION
**Pull request by Thomas-Barbier-1A**
## Changes

Added missing header file in `hex.h`, required to declare `uint8_t`

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [X] Changes in public API reviewed

### CODE REVIEW

**Review by owent — APPROVED** [review]
LGTM once the CLA is signed

**Review by lalitb — APPROVED** [review]

**Comment by Thomas-Barbier-1A** [comment]
Thank you very much! I should be able to get the CLA signed by Monday: There is already an agreement in my company but I need to be added to a list of contributors by someone who will be back on Monday.

**Review by ThomsonTan — APPROVED** [review]
Thanks for the fix. Please also fix the format of include order.

**Comment by Thomas-Barbier-1A** [comment]
Sorry for the delay, it took me a bit more time to get the CLA is signed. But it is now dsigned :-)

**Pull request merged**
