### PR TITLE
Apparent Log Macro Bug Fix

### PR DESCRIPTION
**Pull request by jaelrod**
## Changes

Correctly defines empty `OTEL_INTERNAL_LOG_WARN` macro instead of re-defining empty `OTEL_INTERNAL_LOG_ERROR`.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by lalitb — APPROVED** [review]
Thanks for the fix.

**Review by owent — APPROVED** [review]
LGTM and thanks.

**Comment by lalitb** [comment]
blocked on #2266

**Comment by lalitb** [comment]
Force merging this, as the CI failure is not related to the bug fix. Looking into the CI failure separately in #2266.

**Pull request merged**
