### PR TITLE
[DOC] Fix typo in benchmarks.rst

### PR DESCRIPTION
**Pull request by orion160**
Docs typo.

### CODE REVIEW

**Review by marcalff — COMMENTED** [review]
Thanks for pointing out the typo.

I think the proper word is `fluctuation`

https://dictionary.cambridge.org/dictionary/english/fluctuation

**Comment by marcalff** [comment]
@orion160 

Thanks for the fix.

Please:

* change to `fluctuation` instead
* sign the `CLA` so this can be merged.

**Comment by orion160** [comment]
Done!

**Review by lalitb — APPROVED** [review]

**Review by marcalff — APPROVED** [review]
Thanks for the fix.

**Pull request merged**
