### PR TITLE
[BUILD] Version opentelemetry_proto/proto_grpc shared libraries

### PR DESCRIPTION
**Pull request by Troels51**
After building opentelemetry-cpp with "OTELCPP_VERSIONED_LIBS=ON" I noticed that opentelemetry-proto and opentelemetry-proto-grpc were not versioned

## Changes
This versions opentelemetry_proto and opentelemetry_proto_grpc with set_target_version

One question:
Should these be versioned with the opentelemetry-proto version instead of the SDK version?

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by lalitb — COMMENTED** [review]
@Troels51 Changes look good. However you need to sign the CLA before it can be merged.

**Comment by Troels51** [comment]
Thanks for the quick responses. The CLA is waiting for a signature from a guy on vacation. If it makes things easier we can close and reopen later

**Comment by marcalff** [comment]
> Thanks for the quick responses. The CLA is waiting for a signature from a guy on vacation. If it makes things easier we can close and reopen later

Thanks for the update.
Just keep the PR open, so we will not forget about it.

**Review by owent — APPROVED** [review]
LGTM after CLA is signed.

**Comment by esigo** [comment]
@Troels51 any updates on CLA?

**Comment by Troels51** [comment]
@esigo. The CLA should now be signed :tada:

**Pull request merged**
