### PR TITLE
Use the Google naming convention.

### LINKED ISSUE #5: Choose C++ style guideline
C++ is a big language that can be used in many different ways. We need to choose a style and stick to it.

A couple popular starting points (can be chosen as is or as the starting point for our own style):
- https://google.github.io/styleguide/cppguide.html
- http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines

Other style suggestions are welcome.

### PR DESCRIPTION
**Pull request by g-easy**
Part of #5.

### CODE REVIEW

**Comment by g-easy** [comment]
We discussed this during today's SIG meeting.

**Comment by rnburn** [comment]
Can change this to refer just to the Google naming convention, not the full style guide

**Comment by g-easy** [comment]
@rnburn I'd like to apply most of the style guide, e.g. Output Parameters. How should I change the wording?

Also, we should document exceptions like:
* API should not use features newer than C++11.
* API must be header only.
* Don't use STL types in the API.

**Comment by rnburn** [comment]
Can we limit this PR to just what we agreed to on the call (which was the naming convention)? 

Maybe don't use it to close #5 if you want to further debate the non-naming parts of a style guide.

I would prefer to take CppCore guideline over Google style guide for other parts (they use references for [Output parameters](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-inout)).

**Comment by g-easy** [comment]
Ah, ok. I've updated the PR.

**Comment by g-easy** [comment]
Please remind me: how many approvals do I need before it's okay to merge? :)

**Comment by reyang** [comment]
> Please remind me: how many approvals do I need before it's okay to merge? :)

https://github.com/open-telemetry/opentelemetry-cpp/blob/master/CONTRIBUTING.md#how-to-get-prs-merged

**Pull request merged**
