### PR TITLE
Added s390x arch into CMake build.

### PR DESCRIPTION
**Pull request by velemas**
Signed-off-by: Artiom Vaskov <Artiom.Vaskov@ibm.com>

Fixes # (issue)

## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by esigo** [comment]
@velemas thanks for the PR. 
Could you please fix CLA [error](https://github.com/open-telemetry/opentelemetry-cpp/pull/1216#issuecomment-1041495461)?

**Review by lalitb — APPROVED** [review]

**Review by ThomsonTan — APPROVED** [review]

**Comment by lalitb** [comment]
@velemas - Would you be working to fix CLA, so that the PR can be merged?

**Comment by velemas** [comment]
@lalitb yes, i'm working on it, sorry for the delay

**Comment by ThomsonTan** [comment]
> @lalitb yes, i'm working on it, sorry for the delay

Seems the CLA is still not done. @velemas please let us know if there is any issue.

**Comment by velemas** [comment]
@ThomsonTan it's just a long internal process, hope by the end of the week it is done.

**Pull request merged**
