### PR TITLE
Prepare v1.8.3 release

### LINKED ISSUE #2007: Prepare release v.1.9.0 (tentative: 3rd March)
There are few Open PRs which preferably be merged (not in order of priority) before creating the release:

* #2005 
* #2004 
* #2000 
* #1993 
* #1909 

#2000 is  ABI breaking change for the SDK which should be fine in general. But it also means that if someone is using otel-cpp-sdk*so targets with their application, the application can crash if these shared library is rebuild for new version, without recompiling/relinking the application against these new shared libraries. This needs to be mentioned in the release notes.

### PR DESCRIPTION
**Pull request by ThomsonTan**
Fixes #2007 

## Changes

Without including #2000 and #2005, this release is considered as a patch release.

For significant contributions please make sure you have completed the following items:

* [x] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by ThomsonTan** [comment]
> clang-format failed.
> 
> Please reformat the code located inside the pre-commit script:
> 
> ```
> const int major_version = ${major};
> const int minor_version = ${minor};
> const int patch_version = ${patch};
> const char* pre_release = "${pre_release}";
> const char* build_metadata = "${build_metadata}";
> const int count_new_commits = ${count_new_commits};
> const char* branch = "${branch}";
> const char* commit_hash = "${latest_commit_hash}";
> const char* short_version = "${short_version}";
> const char* full_version =
>     "${full_version}";
> const char* build_date = "$(date -u)";
> ```
> 
> so that the generated code is correctly formatted by default, removing the need to apply clang-format by hand after generation.

Updated the pre-commit scripts accordingly.

**Review by marcalff — COMMENTED** [review]
There are a few PR ready to be merged:

* https://github.com/open-telemetry/opentelemetry-cpp/pull/2025
* https://github.com/open-telemetry/opentelemetry-cpp/pull/2022
* https://github.com/open-telemetry/opentelemetry-cpp/pull/2021

Should we wait for them so they get included in the release ?

It will mean to run the pre commit script again.

Also, this release contains windows DDL and the opentracing shim,
so I think it should be named 1.9.0 anyway.

For PR #2000 and #2005, I assume it will take some time to review, due to size.

No strong opinion on wait versus release now.

**Comment by ThomsonTan** [comment]
> There are a few PR ready to be merged:
> 
> * #2025
> * #2022
> * #2021
> 
> Should we wait for them so they get included in the release ?
> 
> It will mean to run the pre commit script again.
> 
> Also, this release contains windows DLL and the opentracing shim, so I think it should be named 1.9.0 anyway.
> 
> For PR #2000 and #2005, I assume it will take some time to review, due to size.
> 
> No strong opinion on wait versus release now.

For Windows DLL, it is a new feature and doesn't change any existing behavior, so I think keep the minor version is fine. For opentracing shim, probably the same applies? @marcalff @lalitb @esigo @owent how do you think?

For the listed small PRs, #2025 #2021 #2022, I suggest we don't merge them before merging this PR, unless it is necessary. So they can get more time in the repo to stabilize, and avoid risks on last-minute changes.

**Comment by esigo** [comment]
> > There are a few PR ready to be merged:
> > 
> > * #2025
> > * #2022
> > * #2021
> > 
> > Should we wait for them so they get included in the release ?
> > 
> > It will mean to run the pre commit script again.
> > 
> > Also, this release contains windows DLL and the opentracing shim, so I think it should be named 1.9.0 anyway.
> > 
> > For PR #2000 and #2005, I assume it will take some time to review, due to size.
> > 
> > No strong opinion on wait versus release now.
> 
> For Windows DLL, it is a new feature and doesn't change any existing behavior, so I think keep the minor version is fine. For opentracing shim, probably the same applies? @marcalff @lalitb @esigo @owent how do you think?
> 
> For the listed small PRs, #2025 #2021 #2022, I suggest we don't merge them before merging this PR, unless it is necessary. So they can get more time in the repo to stabilize, and avoid risks on last-minute changes.

I'd say let's not rush the remaining PRs. Patch release would be fine IMO. 
Thanks

**Comment by ThomsonTan** [comment]
> > > There are a few PR ready to be merged:
> > > 
> > > * [Fix compile error with GCC 11.3 #2025](https://github.com/open-telemetry/opentelemetry-cpp/pull/2025)
> > > * [Add `OPENTELEMETRY_INSTALL` to allow user to skip install targets. #2022](https://github.com/open-telemetry/opentelemetry-cpp/pull/2022)
> > > * [Fix syntax issue in pre-release script #2021](https://github.com/open-telemetry/opentelemetry-cpp/pull/2021)
> > > 
> > > Should we wait for them so they get included in the release ?
> > > It will mean to run the pre commit script again.
> > > Also, this release contains windows DLL and the opentracing shim, so I think it should be named 1.9.0 anyway.
> > > For PR #2000 and #2005, I assume it will take some time to review, due to size.
> > > No strong opinion on wait versus release now.
> > 
> > 
> > For Windows DLL, it is a new feature and doesn't change any existing behavior, so I think keep the minor version is fine. For opentracing shim, probably the same applies? @marcalff @lalitb @esigo @owent how do you think?
> > For the listed small PRs, #2025 #2021 #2022, I suggest we don't merge them before merging this PR, unless it is necessary. So they can get more time in the repo to stabilize, and avoid risks on last-minute changes.
> 
> I'd say let's not rush the remaining PRs. Patch release would be fine IMO. Thanks

Seems #2022 has been merged. Then we can take the chance to merge the other 2 small PRs because we need to re-run the pre-commit script anyway.

**Comment by ThomsonTan** [comment]
All 3 PRs listed above were merged. I am going to run `pre-commit` here and update.

**Review by marcalff — APPROVED** [review]
LGTM.

Nit - release date in CHANGELOG is [1.8.3] 2023-03-06, should be [1.8.3] 2023-03-07

**Review by lalitb — APPROVED** [review]

**Comment by owent** [comment]
> they

Agree not to merge these new features.We can include them in 1.9.0 later.

**Comment by ThomsonTan** [comment]
> > they
> 
> Agree not to merge these new features.We can include them in 1.9.0 later.

Apologize for the confusion. As one of the smaller PR had already been merged when I made the request, I proceeded to merge all remaining smaller PRs and updated this release accordingly.

I will be more careful and send a notice to freeze the merge before our next release.

**Pull request merged**
