### PR TITLE
Add options to construct BatchSpanProcessor

### PR DESCRIPTION
**Pull request by bogdandrutu**
Fixes https://github.com/open-telemetry/opentelemetry-cpp/issues/497

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by ThomsonTan — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@ThomsonTan I have a small problem with format :) I have a newer version and thought may be good to upgrade everything to the clang-format-11, is that ok?

See https://github.com/open-telemetry/opentelemetry-cpp/pull/544, then I will format this as well.

**Review by jsuereth — APPROVED** [review]

**Comment by ThomsonTan** [comment]
> @ThomsonTan I have a small problem with format :) I have a newer version and thought may be good to upgrade everything to the clang-format-11, is that ok?
> 
> See #544, then I will format this as well.

Yes, it should work. You can update this PR once #544 is merged. @lalitb FYI.

**Review by pyohannes — APPROVED** [review]

**Comment by lalitb** [comment]
> > @ThomsonTan I have a small problem with format :) I have a newer version and thought may be good to upgrade everything to the clang-format-11, is that ok?
> > See #544, then I will format this as well.
> 
> Yes, it should work. You can update this PR once #544 is merged. @lalitb FYI.

@bogdandrutu -  Thanks for the change. The `format` check was successful for this PR ( with clang-format-10), so I will go ahead and merge, unless you plan to do some change ?

**Comment by lalitb** [comment]
> > > @ThomsonTan I have a small problem with format :) I have a newer version and thought may be good to upgrade everything to the clang-format-11, is that ok?
> > > See #544, then I will format this as well.
> > 
> > 
> > Yes, it should work. You can update this PR once #544 is merged. @lalitb FYI.
> 
> @bogdandrutu - Thanks for the change. The `format` check was successful for this PR ( with clang-format-10), so will go ahead and merge, unless you plan to add something further ?

LGTM. will go ahead and merge.

**Pull request merged**
