### PR TITLE
[TEST] Fix sync problems in OTLP File exporter tests.

### LINKED ISSUE #3025: [TEST] test failure in otlp_file_exporter_test
The following test fails with bazel + valgrind:

```
FAIL: //exporters/otlp:otlp_file_exporter_test (see /home/runner/.cache/bazel/e6b8d6759295e14b76bc8cb98b604748/execroot/_main/bazel-out/k8-fastbuild/testlogs/exporters/otlp/otlp_file_exporter_test/test.log)
INFO: From Testing //exporters/otlp:otlp_file_exporter_test:
==================== Test output for //exporters/otlp:otlp_file_exporter_test:
==11== Memcheck, a memory error detector
==11== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==11== Command: exporters/otlp/otlp_file_exporter_test
==11== 
Running main() from gmock_main.cc
[==========] Running 2 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from OtlpFileExporterTest
[ RUN      ] OtlpFileExporterTest.Shutdown
Error:  File: exporters/otlp/src/otlp_file_exporter.cc:55 [OTLP TRACE FILE Exporter] ERROR: Export 0 trace span(s) failed, exporter is shutdown
[       OK ] OtlpFileExporterTest.Shutdown (87 ms)
[----------] 1 test from OtlpFileExporterTest (93 ms total)

[----------] 1 test from OtlpFileExporterTestPeer
[ RUN      ] OtlpFileExporterTestPeer.ExportJsonIntegrationTestSync
unknown file: Failure
C++ exception with description "[json.exception.type_error.305] cannot use operator[] with a string argument with discarded" thrown in the test body.

[  FAILED  ] OtlpFileExporterTestPeer.ExportJsonIntegrationTestSync (2717 ms)
[----------] 1 test from OtlpFileExporterTestPeer (2720 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 2 test suites ran. (2869 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] OtlpFileExporterTestPeer.ExportJsonIntegrationTestSync

 1 FAILED TEST
==11== 
==11== HEAP SUMMARY:
==11==     in use at exit: 0 bytes in 0 blocks
==11==   total heap usage: 8,401 allocs, 8,401 frees, 711,058 bytes allocated
==11== 
==11== All heap blocks were freed -- no leaks are possible
==11== 
==11== For lists of detected and suppressed errors, rerun with: -s
==11== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
================================================================================
```

### PR DESCRIPTION
**Pull request by owent**
Fixes #3025

## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [x] Changes in public API reviewed

### CODE REVIEW

**Review by marcalff — APPROVED** [review]
LGTM, thanks for the test cleanup.

**Review by marcalff — COMMENTED** [review]
The code change looks ok, but the test still fails under valgrind.

There must be another root cause to fix.

**Comment by owent** [comment]
`nlohmann::json::parse` seems parse json text failed, still try to find out the reason.

**Comment by marcalff** [comment]
> `nlohmann::json::parse` seems parse json text failed, still try to find out the reason.

I have not found anything either.

Let's merge this, in hope that the next failure will bring more information about the root cause.

**Review by marcalff — APPROVED** [review]
Ok to merge.

This will help narrow the root cause, so it can be better investigated.

**Pull request merged**
