### PR TITLE
Remove implicitly deleted default constructor

### PR DESCRIPTION
**Pull request by benlandrum**
Fix a Clang warning about an implicitly deleted default constructor.

```
warning: explicitly defaulted default constructor is implicitly deleted [-Wdefaulted-function-deleted]
Token() noexcept = default;
^
note: default constructor of 'Token' is implicitly deleted because field 'context_' of const-qualified type 'const opentelemetry::context::Context' would not be initialized
const Context context_;
              ^
```

## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by lalitb — APPROVED** [review]
Thanks for the fix. I thought this was fixed by #774 but seems that change didn't go through. You would need to sign EasyCLA for this to go through :)

**Review by ThomsonTan — APPROVED** [review]

**Comment by benlandrum** [comment]
Working on the CLA, @lalitb. Thank you.

**Comment by lalitb** [comment]
@benlandrum  - Would you be working on CLA ?

**Comment by lalitb** [comment]
@benlandrum  - Would you be working on CLA ?

**Comment by benlandrum** [comment]
> @benlandrum - Would you be working on CLA ?

@lalitb, sorry for the wait, and thanks for the reminder. I should have approval in a day or so.

**Comment by benlandrum** [comment]
@lalitb approved.

**Pull request merged**
