### PR TITLE
🐛 Fix for Stack::Resize that new_capacity is not assigned to capacity_

### PR DESCRIPTION
**Pull request by Yerannnnnn**
## Changes

Fix for Stack::Resize that new_capacity is not assigned to capacity_ , caused stack to constantly allocate memory when size_>0.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by Yerannnnnn** [comment]
`is not authorized under a signed CLA. Please click here to be authorized.`　

I cliecked it then got  `{"message": "Internal server error"}`

something wrong?

**Comment by lalitb** [comment]
@Yerannnnnn  - Can you try to authorize yourself for easyCLA now?

**Review by lalitb — APPROVED** [review]

**Review by ThomsonTan — APPROVED** [review]

**Comment by Yerannnnnn** [comment]
> @Yerannnnnn - Can you try to authorize yourself for easyCLA now?

@lalitb  Done

**Pull request merged**
