### PR TITLE
Update `opentelemetry-proto` submodule to version from May 18, 2021

### PR DESCRIPTION
**Pull request by maxgolov**
Update `opentelemetry-proto` submodule from 5 months old to latest version:

```text
commit 795cc815ce9bb438b46a4a7f6ecb465b52d50935 (HEAD -> main, origin/main, origin/HEAD)
Author: Bogdan Drutu <bogdandrutu@gmail.com>
Date:   Tue May 18 14:42:43 2021 -0700
```

No other code changes.

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Comment by ThomsonTan** [comment]
Is it more conservative to snap the latest tag instead of main branch?

**Comment by maxgolov** [comment]
> Is it more conservative to snap the latest tag instead of main branch?

My understanding is it's generally both `safer` and `more predictable` to track to specific commit. And the usual flow is:

```console
cd submodule
git pull
cd ..
git add submodule
git commit -m "Updated version to X"
```

This guarantees that by default when you perform recursive cloning, you get a set of deps that is guaranteed to work / passes CI.

**Comment by lalitb** [comment]
Thanks for the update. Should we also update the proto package used by bazel as part of this PR:

https://github.com/open-telemetry/opentelemetry-cpp/blob/93dd39bd921cd20cf0537d18565fc9cd4d8dcad8/bazel/repository.bzl#L48

**Comment by lalitb** [comment]
Merging now. For bazel, we can do it in separate PR.

**Pull request merged**
