### PR TITLE
Allow to build library without tests and examples

### PR DESCRIPTION
**Pull request by avsej**
* tests for memory exporters are not guarded by `BUILD_TESTING`
* `include(CTest)` itself, with internally defines `BUILD_TESTING` have to be optional  
* expose `WITH_EXAMPLES` option to allow skipping examples

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Review by ThomsonTan — APPROVED** [review]

**Review by pyohannes — APPROVED** [review]

**Comment by avsej** [comment]
completed `cmake-format -i` on both files, hopefully it will make CI happy

**Comment by avsej** [comment]
@reyang @ThomsonTan @pyohannes, could you help me with your `cmake-format` setup? your project does not have `.cmake-format.yaml` and it seems like CI is using some pretty old version of `cmake-format`.

**Comment by lalitb** [comment]
> @reyang @ThomsonTan @pyohannes, could you help me with your `cmake-format` setup? your project does not have `.cmake-format.yaml` and it seems like CI is using some pretty old version of `cmake-format`. Feel free to update my patch if necessary, I just want to use the library but don't want to build and run testsuite.

`Buildifier` is used for formatting. you need to first install it by running this [script](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/ci/install_format_tools.sh),  and then do formatting using `ci/do-ci.sh format` from [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/5c8911415a0457afe334c1f09939f1c6d12061ee/ci/do_ci.sh#L153). Ensure to commit formatted file.

**Comment by avsej** [comment]
Thank you, @lalitb. Now it looks good. The problem was really in that the CI is using outdated `cmake-format`.

**Comment by ThomsonTan** [comment]
What's the current stable version of cmake-format? Perhaps we should upgrade it to avoid such kind of spurious CI failure.

**Comment by avsej** [comment]
cmake-format 0.6.13 
https://pypi.org/project/cmake-format/

**Pull request merged**
