### PR TITLE
[Metrics SDK] Cleanup of old _metric api/sdk

### PR DESCRIPTION
**Pull request by esigo**
This does cleanup as part of #1573 - delete files under api//_metrics, sdk//_metrics directory.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [x] Changes in public API reviewed

### CODE REVIEW

**Review by owent — COMMENTED** [review]
`prometheus_exporter_deprecated` in `cmake/opentelemetry-cpp-config.cmake.in` can also be removed.

**Comment by esigo** [comment]
> `prometheus_exporter_deprecated` in `cmake/opentelemetry-cpp-config.cmake.in` can also be removed.

Thanks @owent, done

**Review by marcalff — APPROVED** [review]
LGTM.

**Review by lalitb — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
