### PR TITLE
Use latest TraceLoggingDynamic.h

### PR DESCRIPTION
**Pull request by lalitb**
To incorporate these changes: https://github.com/microsoft/tracelogging/pull/37

### CODE REVIEW

**Comment by ThomsonTan** [comment]
The diff implying more changes in the linked PR?

**Review by ThomsonTan — APPROVED** [review]

**Comment by lalitb** [comment]
> The diff implying more changes in the linked PR?

Yes, there are more changes as comments, but I think no harm in picking them.

**Comment by reyang** [comment]
Couple logistic questions:
1. Would submodules help here https://github.com/open-telemetry/opentelemetry-cpp/blob/main/.gitmodules?
2. Do we need to also include the [license file](https://github.com/microsoft/tracelogging/blob/main/LICENSE)?

**Review by esigo — APPROVED** [review]
LGTM
Thanks for the PR :)

**Comment by ThomsonTan** [comment]
Is the license added just a copy of https://github.com/microsoft/tracelogging/blob/main/LICENSE, there seems a slight difference.

**Comment by lalitb** [comment]
> Is the license added just a copy of https://github.com/microsoft/tracelogging/blob/main/LICENSE, there seems a slight difference.

It's taken from there - https://github.com/microsoft/tracelogging-dynamic-windows which is actually our upstream source. I will raise a PR on this repo for the fix too.

**Pull request merged**
