### PR TITLE
Enable running otlp exporter unit-tests on ubuntu.

### LINKED ISSUE #573: Enable otlp exporter tests to build and run using cmake on ubuntu-latest.
As of now, not all the otlp exporter tests are building and running on ubuntu-latest even with WITH_OTLP=ON.  

The exporter tests here : https://github.com/open-telemetry/opentelemetry-cpp/blob/main/exporters/otlp/test/otlp_exporter_test.cc are not enabled to build and run through [CMakeLists.txt ](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/exporters/otlp/CMakeLists.txt). As an example, see the github workflow here: https://github.com/open-telemetry/opentelemetry-cpp/runs/1874066873?check_suite_focus=true which doesn't run mentioned tests.

Reason seems to be :
 - Missing gmock library ( [setup_cmake.sh](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/ci/setup_cmake.sh) to be modified to build and install gmock )
 - Missing grpc mock services for traces ( Needs changes in [opentelemetry-proto.cmake](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/cmake/opentelemetry-proto.cmake) to create these mocks )
 - gmock package missing for cmake (  ? )

### PR DESCRIPTION
**Pull request by lalitb**
Fixes #573 
## Changes

Please provide a brief description of the changes here.
Small fix to
 - Enables mock stub generation for otel proto services.
 - Build and Install google-mock library for ubuntu.
 - Modify otlp-exporter cmakefile to run these mock [tests](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/exporters/otlp/test/otlp_exporter_test.cc)

Validated that these tests are running 
 
For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by ThomsonTan** [comment]
Which part of the test does rely on gmock?

**Comment by lalitb** [comment]
> Which part of the test does rely on gmock?

The mock stub generated by protoc has dependency on gmock.

**Comment by ThomsonTan** [comment]
Seems the CMake build/test failed, @lalitb could you please take a look?

**Comment by lalitb** [comment]
> Seems the CMake build/test failed, @lalitb could you please take a look?

Thanks, seems to have timed-out while fetching the packages, hopefu;lly re-running would be successful.

**Comment by lalitb** [comment]
> > Seems the CMake build/test failed, @lalitb could you please take a look?
> 
> Thanks, seems to have timed-out while fetching the packages, hopefully re-run would be successful.

It's all passing now. Thanks for letting me know.

**Review by ThomsonTan — APPROVED** [review]

**Pull request merged**
