### PR TITLE
Fix:1676 Segfault when short export period is used for metrics 

### LINKED ISSUE #1676: [Metrics SDK] Segfault when short export period is used for metrics
We're experiencing segfaults when using async instruments with a relatively short (e.g. `OTEL_METRICS_EXPORT_INTERVAL_MILLIS=100 OTEL_METRICS_EXPORT_TIMEOUT_MILLIS=50`) export period.

For me, this looks like a race condition issue and strongly resembles https://github.com/open-telemetry/opentelemetry-cpp/issues/1663 , but it's still present after bumping `opentelemetry-cpp` to the last commit.

I was able to catch this with GDB, here's the stack trace:
[(gdb)_backtrace_full.txt](https://github.com/open-telemetry/opentelemetry-cpp/files/9766970/gdb._backtrace_full.txt)

If necessary, I'll try to put together a self-contained reproducer, but I'm hoping that it's something simple. :)

### PR DESCRIPTION
**Pull request by lalitb**
Fixes #1676 

## Changes

MeterContext::ForceFlush() is incorrectly setting shutdown latch. Later when MeterContext::Shutdown() is invoked, the latch is already set, and shutdown is not done.

The PR would have merge conflict with #1673.

@ahadnagy  - If you would like to test the changes, I got the segfault with with your code during MeterProvider shutdown, and this fixes that. I am hoping it was the same crash you observed :)

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [x] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by esigo — APPROVED** [review]
LGTM
Thanks for the fix :)
let's wait for #1650 to merge first.

**Comment by ahadnagy** [comment]
@lalitb I had a chance to try this today, and looks like it's solved the issue! Thanks a lot for fixing this so quickly!

**Review by ahadnagy — APPROVED** [review]
@lalitb I had a chance to try this today, and looks like it's solved the issue! Thanks a lot for fixing it so quickly!

**Comment by lalitb** [comment]
> @lalitb I had a chance to try this today, and looks like it's solved the issue! Thanks a lot for fixing it so quickly!

Thanks for confirming. Also calling MeterProvider->Shutdown() is now optional, as it would be called as part of MeterProvider destruction. Have added that change in this PR.

**Pull request merged**
