### PR TITLE
[EXPORTER] Fix crash in ElasticsearchLogRecordExporter

### LINKED ISSUE #3078: ElasticSearch exporter crashes when emitting a log (EXC_BAD_ACCESS)
**Describe your environment** 

Using a manually built version of OpenTelemetry 1.16.1 on macOS with :

```
    -DWITH_EXAMPLES=OFF
    -DWITH_OTLP_HTTP=ON
    -DBUILD_TESTING=OFF
    -DWITH_OTLP_GRPC=OFF
    -DWITH_LOGS_PREVIEW=ON
    -DOPENTELEMETRY_INSTALL=ON
    -DBUILD_SHARED_LIBS=OFF
    -DWITH_ASYNC_EXPORT_PREVIEW=ON
    -DCMAKE_CXX_STANDARD=17
    -DWITH_ELASTICSEARCH=ON
```

**Steps to reproduce**

The usage is pretty simple:

First an init of the exporter with a single log record processor:

```cpp
opentelemetry::exporter::logs::ElasticsearchExporterOptions opts(
    <host>,
    9200,
    "logs",
    30,
    true);

auto elkExporter = std::make_unique<opentelemetry::exporter::logs::ElasticsearchLogRecordExporter>(opts);

auto elkProcessor = opentelemetry::sdk::logs::SimpleLogRecordProcessorFactory::Create(std::move(elkExporter));
            
std::shared_ptr<opentelemetry::logs::LoggerProvider> provider = opentelemetry::sdk::logs::LoggerProviderFactory::Create(
    std::move(elkProcessor), resource);

opentelemetry::logs::Provider::SetLoggerProvider(provider);

m_Logger = provider->GetLogger("MyLogger", SOURCE_NAME);
```

Then, when logs needs to be sent a call to `m_Logger.EmitLogRecord(xxx)`

**What is the expected behavior?**
The program should run and send the log to the ELK endpoint.

**What is the actual behavior?**
It crashes on `es_log_record_exporter.cc:353`

```
 thread #5, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001011d2e44 `unsigned long std::__1::__cxx_atomic_fetch_add<unsigned long>(__a=0x0000000000000000, __delta=1, __order=memory_order_release) at atomic:1050:12
   1047	template<class _Tp>
   1048	_LIBCPP_INLINE_VISIBILITY
   1049	_Tp __cxx_atomic_fetch_add(__cxx_atomic_base_impl<_Tp> * __a, _Tp __delta, memory_order __order) _NOEXCEPT {
-> 1050	    return __c11_atomic_fetch_add(&__a->__a_value, __delta, static_cast<__memory_order_underlying_t>(__order));
   1051	}
   1052
   1053	template<class _Tp>
```

Backtrace:
```  
frame #0: 0x00000001011d2e44 `unsigned long std::__1::__cxx_atomic_fetch_add<unsigned long>(__a=0x0000000000000000, __delta=1, __order=memory_order_release) at atomic:1050:12
frame #1: 0x00000001011c06ec `std::__1::__atomic_base<unsigned long, true>::fetch_add(this=0x0000000000000000, __op=1, __m=memory_order_release) at atomic:1719:17
frame #2: 0x00000001011bfedc `opentelemetry::v1::exporter::logs::ElasticsearchLogRecordExporter::Export(this=0x000060000079bf80, records=0x000000017002a960) at es_log_record_exporter.cc:353:43
frame #3: 0x0000000101214f08 `opentelemetry::v1::sdk::logs::SimpleLogRecordProcessor::OnEmit(this=0x00006000029c1d20, record=nullptr) at simple_log_record_processor.cc:48:18
frame #4: 0x0000000101227b40 `opentelemetry::v1::sdk::logs::MultiLogRecordProcessor::OnEmit(this=0x00006000029c1d40, record=opentelemetry::v1::sdk::logs::Recordable @ 0x00006000027a0de0) at multi_log_record_processor.cc:70:18
frame #5: 0x000000010120be40 `opentelemetry::v1::sdk::logs::Logger::EmitLogRecord(this=0x0000600003c9c440, log_record=0x000000017002ab50) at logger.cc:109:13
frame #6: 0x0000000100b63bc0 `void opentelemetry::v1::logs::Logger::EmitLogRecord<opentelemetry::v1::logs::Severity, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&, opentelemetry::v1::common::SystemTimestamp>(this=0x0000600003c9c440, log_record=0x000000017002ab50, args=0x000000017002abf7, args=Summary Unavailable, args=size=0, args=0x000000017002abe8) at logger.h:79:5
```

**Additional context**
There is no problem if using a `HttpLogRecordExporter`  instead of a `ElasticsearchLogRecordExporter` with the exact samecode

### PR DESCRIPTION
**Pull request by ShadowMaxLeb**
Fixes #3078

Using constructor with user provided options in `ElasticsearchLogRecordExporter` was making the program crash due to `synchronization_data_` not being intialized when built with async behavior (`-DWITH_ASYNC_EXPORT_PREVIEW=ON`)

## Changes

Constructors have been changed so the default one always calls the one with options as parameters to ensure to always initialize everything.

### CODE REVIEW

**Comment by marcalff** [comment]
Thanks @ShadowMaxLeb for the patch.

Please sign the contributor agreement (CLA), so this PR can be merged to the main branch.
The CLA will apply to all PR, present and future, so it only needs to be done once.

**Review by marcalff — APPROVED** [review]
LGTM, thanks for the fix.

**Comment by marcalff** [comment]
@ShadowMaxLeb 

Thanks for the contribution.

This PR is approved and ready to be merged to the main branch.
Unfortunately, we (opentelemetry-cpp maintainers) do not have github permissions to update this branch.
This is needed to:

* perform a main -> PR merge first, to align the PR branch to main
* perform the PR -> main merge, to accept the contribution.

Please allow maintainers to make edits (there is a checkbox in the github UI for that), or perform a main -> PR merge to we can take it.

Thanks.

**Comment by marcalff** [comment]
Added the merge conflict tag.
There are no merge conflicts, only the down merge needs to be resolved:
> This branch is out-of-date with the base branch

**Review by lalitb — APPROVED** [review]

**Comment by ShadowMaxLeb** [comment]
Since the fork ispart of an organization, it seems that I do not have the possibility to allow maintainers (https://github.com/orgs/community/discussions/5634).

I will update the PR.

**Pull request merged**
