### PR TITLE
Upgraded semantic conventions to 1.19.0

### LINKED ISSUE #2016: [SEMANTIC CONVENTIONS] Upgrade to version 1.19.0
opentelemetry-specification 1.19.0 is ~about to be~ released (planned 2023-03-06).

* https://github.com/open-telemetry/opentelemetry-specification/pull/3285

Run code generation again to align on spec 1.19.0.

### PR DESCRIPTION
**Pull request by marcalff**
Fixes #2016

## Changes

Upgraded semantic conventions to 1.19.0

For significant contributions please make sure you have completed the following items:

* [X] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [X] Changes in public API reviewed

### CODE REVIEW

**Review by ThomsonTan — APPROVED** [review]

**Comment by marcalff** [comment]
On hold for now, there is something wrong with code generation, a lot of semconv are missing.

**Comment by marcalff** [comment]
Blocked by:

* https://github.com/open-telemetry/opentelemetry-specification/issues/3299

**Comment by marcalff** [comment]
Unblocked by:

* https://github.com/open-telemetry/build-tools/pull/157

build-tools 0.18.0 resolves code generation.

**Review by lalitb — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
