### PR TITLE
[bazel] Enable --incompatible_disallow_empty_glob

### PR DESCRIPTION
**Pull request by keith**
This way downstream consumers can enable this flag as well

### CODE REVIEW

**Comment by malkia** [comment]
I have a list in my soft fork, with few more incompatbiles that were enabled (whatever I can) - https://github.com/malkia/opentelemetry-cpp/blob/main/.bazelrc#L92 - although that specifically did not work - I think it was for the prometheus-cpp module?

**Comment by keith** [comment]
depends on https://github.com/jupp0r/prometheus-cpp/pull/715 and probably some other stuff

**Comment by marcalff** [comment]
> depends on [jupp0r/prometheus-cpp#715](https://github.com/jupp0r/prometheus-cpp/pull/715) and probably some other stuff

This PR in prometheus-cpp:

* https://github.com/jupp0r/prometheus-cpp/pull/715

is merged, but there is no release yet that includes it.

Opentelemetry-cpp is using the prometheus-cpp 1.2.4 tag.

Waiting on release 1.2.5 from prometheus.

**Comment by marcalff** [comment]
Related:

* https://github.com/jupp0r/prometheus-cpp/issues/722

**Comment by keith** [comment]
will rebase after https://github.com/open-telemetry/opentelemetry-cpp/pull/3162

**Review by marcalff — APPROVED** [review]
LGTM, thanks for the fix.

**Pull request merged**
