### PR TITLE
Fix compile with clang 16 and libc++

### LINKED ISSUE #2241: Can not compile with clang 16 and libc++
**Describe your environment**

OS: Linux
Compiler: Clang 16.0.6 with libc++

**What is the actual behavior?**

```bash
[ 50%] Building CXX object sdk/src/logs/CMakeFiles/opentelemetry_logs.dir/simple_log_record_processor_factory.cc.o
In file included from /data/workspace/third_party/packages/opentelemetry-cpp-v1.10.0/sdk/src/logs/simple_log_record_processor_factory.cc:6:
In file included from /data/workspace/third_party/packages/opentelemetry-cpp-v1.10.0/sdk/include/opentelemetry/sdk/logs/simple_log_record_processor_factory.h:8:
In file included from /opt/llvm-16.0/bin/../include/c++/v1/memory:898:
In file included from /opt/llvm-16.0/bin/../include/c++/v1/__memory/shared_ptr.h:31:
/opt/llvm-16.0/bin/../include/c++/v1/__memory/unique_ptr.h:63:19: error: invalid application of 'sizeof' to an incomplete type 'opentelemetry::sdk::logs::LogRecordExporter'
    static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
                  ^~~~~~~~~~~
/opt/llvm-16.0/bin/../include/c++/v1/__memory/unique_ptr.h:297:7: note: in instantiation of member function 'std::default_delete<opentelemetry::sdk::logs::LogRecordExporter>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
/opt/llvm-16.0/bin/../include/c++/v1/__memory/unique_ptr.h:263:75: note: in instantiation of member function 'std::unique_ptr<opentelemetry::sdk::logs::LogRecordExporter>::reset' requested here
  _LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR_SINCE_CXX23 ~unique_ptr() { reset(); }
                                                                          ^
/data/workspace/third_party/packages/opentelemetry-cpp-v1.10.0/sdk/include/opentelemetry/sdk/logs/simple_log_record_processor.h:36:3: note: in instantiation of member function 'std::unique_ptr<opentelemetry::sdk::logs::LogRecordExporter
>::~unique_ptr' requested here
  ~SimpleLogRecordProcessor() override = default;
  ^
/data/workspace/third_party/packages/opentelemetry-cpp-v1.10.0/sdk/include/opentelemetry/sdk/logs/simple_log_record_processor.h:36:3: note: in defaulted destructor for 'opentelemetry::sdk::logs::SimpleLogRecordProcessor' first required 
here
/data/workspace/third_party/packages/opentelemetry-cpp-v1.10.0/sdk/include/opentelemetry/sdk/logs/simple_log_record_processor_factory.h:17:7: note: forward declaration of 'opentelemetry::sdk::logs::LogRecordExporter'
class LogRecordExporter;
      ^
1 error generated.
gmake[2]: *** [sdk/src/logs/CMakeFiles/opentelemetry_logs.dir/build.make:188: sdk/src/logs/CMakeFiles/opentelemetry_logs.dir/simple_log_record_processor_factory.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:615: sdk/src/logs/CMakeFiles/opentelemetry_logs.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
'/opt/cmake/bin/cmake' '--build' '.'


```

```bash
[ 29%] Building CXX object sdk/src/metrics/CMakeFiles/opentelemetry_metrics.dir/data/circular_buffer.cc.o
/data/workspace/third_party/packages/opentelemetry-cpp-v1.10.0/sdk/src/metrics/data/circular_buffer.cc:58:5: error: no matching function for call to 'fill'
    std::fill(backing.begin(), backing.end(), static_cast<T>(0));
    ^~~~~~~~~
/opt/llvm-16.0/bin/../include/c++/v1/__functional/invoke.h:394:23: note: in instantiation of function template specialization 'opentelemetry::sdk::metrics::(anonymous namespace)::AdaptingIntegerArrayClear::operator()<unsigned char>' requested 
here
    { return          static_cast<_Fp&&>(__f)(static_cast<_Args&&>(__args)...); }
                      ^
/opt/llvm-16.0/bin/../include/c++/v1/__bit_reference:422:1: note: candidate template ignored: could not match '__bit_iterator' against '__wrap_iter'
fill(__bit_iterator<_Cp, false> __first, __bit_iterator<_Cp, false> __last, bool __value)
^
/data/workspace/third_party/packages/opentelemetry-cpp-v1.10.0/sdk/src/metrics/data/circular_buffer.cc:58:5: error: no matching function for call to 'fill'
    std::fill(backing.begin(), backing.end(), static_cast<T>(0));
    ^~~~~~~~~
/opt/llvm-16.0/bin/../include/c++/v1/__functional/invoke.h:394:23: note: in instantiation of function template specialization 'opentelemetry::sdk::metrics::(anonymous namespace)::AdaptingIntegerArrayClear::operator()<unsigned short>' requested
 here
    { return          static_cast<_Fp&&>(__f)(static_cast<_Args&&>(__args)...); }
                      ^
/opt/llvm-16.0/bin/../include/c++/v1/__bit_reference:422:1: note: candidate template ignored: could not match '__bit_iterator' against '__wrap_iter'
fill(__bit_iterator<_Cp, false> __first, __bit_iterator<_Cp, false> __last, bool __value)
^
/data/workspace/third_party/packages/opentelemetry-cpp-v1.10.0/sdk/src/metrics/data/circular_buffer.cc:58:5: error: no matching function for call to 'fill'
    std::fill(backing.begin(), backing.end(), static_cast<T>(0));
    ^~~~~~~~~
/opt/llvm-16.0/bin/../include/c++/v1/__functional/invoke.h:394:23: note: in instantiation of function template specialization 'opentelemetry::sdk::metrics::(anonymous namespace)::AdaptingIntegerArrayClear::operator()<unsigned int>' requested h
ere
    { return          static_cast<_Fp&&>(__f)(static_cast<_Args&&>(__args)...); }
                      ^
/opt/llvm-16.0/bin/../include/c++/v1/__bit_reference:422:1: note: candidate template ignored: could not match '__bit_iterator' against '__wrap_iter'
fill(__bit_iterator<_Cp, false> __first, __bit_iterator<_Cp, false> __last, bool __value)
^
/data/workspace/third_party/packages/opentelemetry-cpp-v1.10.0/sdk/src/metrics/data/circular_buffer.cc:58:5: error: no matching function for call to 'fill'
    std::fill(backing.begin(), backing.end(), static_cast<T>(0));
    ^~~~~~~~~
/opt/llvm-16.0/bin/../include/c++/v1/__functional/invoke.h:394:23: note: in instantiation of function template specialization 'opentelemetry::sdk::metrics::(anonymous namespace)::AdaptingIntegerArrayClear::operator()<unsigned long>' requested 
here
    { return          static_cast<_Fp&&>(__f)(static_cast<_Args&&>(__args)...); }
                      ^
/opt/llvm-16.0/bin/../include/c++/v1/__bit_reference:422:1: note: candidate template ignored: could not match '__bit_iterator' against '__wrap_iter'
fill(__bit_iterator<_Cp, false> __first, __bit_iterator<_Cp, false> __last, bool __value)
^
4 errors generated.
gmake[2]: *** [sdk/src/metrics/CMakeFiles/opentelemetry_metrics.dir/build.make:328: sdk/src/metrics/CMakeFiles/opentelemetry_metrics.dir/data/circular_buffer.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:588: sdk/src/metrics/CMakeFiles/opentelemetry_metrics.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
'/opt/cmake/bin/cmake' '--build' '.' '--verbose'
```

**Additional context**

The problem of `std::fill` may be the BUG of libc++.But we may use `std::vector::assign` to avoid this problem.

### PR DESCRIPTION
**Pull request by owent**
Fixes #2241 

## Changes

+ Move destructor of `SimpleLogRecordProcessor` into `.cc` .
+ Use `std::vector::assign` to replace `std::fill` .

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [x] Changes in public API reviewed

### CODE REVIEW

**Review by marcalff — COMMENTED** [review]
I think the root cause is the forward declaration of LogRecordExporter.

Because of `std::unique_ptr<LogRecordExporter>`, the compiler needs to see the LogRecordExporter destructor, and the header file that declares it.

Please try to include the header file for LogRecordExporter instead.

**Comment by marcalff** [comment]
Per build logs in this PR:

```
2023-07-20T14:35:30.4501309Z Warning: include-what-you-use reported diagnostics:
2023-07-20T14:35:30.4501835Z 
2023-07-20T14:35:30.4502487Z /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/include/opentelemetry/sdk/logs/simple_log_record_processor.h should add these lines:
2023-07-20T14:35:30.4503155Z #include <bits/chrono.h>                           // for microseconds
2023-07-20T14:35:30.4503659Z #include "opentelemetry/sdk/logs/exporter.h"       // for LogRecordExporter
2023-07-20T14:35:30.4504200Z #include "opentelemetry/sdk/logs/recordable.h"     // for Recordable
2023-07-20T14:35:30.4504529Z 
2023-07-20T14:35:30.4505149Z /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/include/opentelemetry/sdk/logs/simple_log_record_processor.h should remove these lines:
2023-07-20T14:35:30.4505824Z - #include <chrono>  // lines 8-8
2023-07-20T14:35:30.4506531Z - namespace opentelemetry { namespace v1 { namespace sdk { namespace logs { class LogRecordExporter; } } } }  // lines 20-20
2023-07-20T14:35:30.4507384Z - namespace opentelemetry { namespace v1 { namespace sdk { namespace logs { class Recordable; } } } }  // lines 21-21
```

Please add the following two lines:

```
#include "opentelemetry/sdk/logs/exporter.h"
#include "opentelemetry/sdk/logs/recordable.h"
```

and remove the matching forward declarations,
in file `sdk/include/opentelemetry/sdk/logs/simple_log_record_processor.h`

Looks like unique_ptr is preventing to use forward declarations.

**Comment by owent** [comment]
> About the first issue:
> 
> I think the root cause is the forward declaration of LogRecordExporter.
> 
> Because of `std::unique_ptr<LogRecordExporter>`, the compiler needs to see the LogRecordExporter destructor, and the header file that declares it.
> 
> Please try to include the header file for LogRecordExporter instead.

The problem is `~SimpleLogRecordProcessor() override = default;` need the definition of `LogRecordExporter`, because it's a member of `SimpleLogRecordProcessor`.

`BatchLogRecordProcessor`, `BatchSpanProcessor` have the similar declarations, do you think it's better to keep the similar includes here?

**Comment by marcalff** [comment]
> > About the first issue:
> > I think the root cause is the forward declaration of LogRecordExporter.
> > Because of `std::unique_ptr<LogRecordExporter>`, the compiler needs to see the LogRecordExporter destructor, and the header file that declares it.
> > Please try to include the header file for LogRecordExporter instead.
> 
> The problem is `~SimpleLogRecordProcessor() override = default;` need the definition of `LogRecordExporter`, because it's a member of `SimpleLogRecordProcessor`.
> 
> `BatchLogRecordProcessor`, `BatchSpanProcessor` have the similar declarations, do you think it's better to keep the similar includes here?

Independently of forwards, I agree that moving code from *.h to *.cc is a good change in general.

My concern is that, even when this fix the immediate issue, there might be more cases where the use of forward declarations with std::unique_ptr causes problems (this is specific to unique_ptr, shared_ptr is working properly and does not need to see the destructor of T).

Revising every forward used in every std::unique_ptr will be a separate change anyway, to analyze in more details, so approving this change.

**Review by marcalff — APPROVED** [review]
LGTM

**Pull request merged**
