### PR TITLE
Upgrade grpc dependency.

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by g-easy** [comment]
Is this new in grpc 1.34? It changes how protoc is pulled in?

(looks like the new grpc release also breaks the gcc-4.8+bazel build)

**Comment by bogdandrutu** [comment]
> Is this new in grpc 1.34? It changes how protoc is pulled in?

I think you added the specific proto dep to work around the bug in the description, but proto is a transitive deps from gRPC, and not sure why we need to redeclare since there is no `cc_library` that has any deps to the proto library. Am I missing something?

**Comment by ThomsonTan** [comment]
> > Is this new in grpc 1.34? It changes how protoc is pulled in?
> 
> I think you added the specific proto dep to work around the bug in the description, but proto is a transitive deps from gRPC, and not sure why we need to redeclare since there is no `cc_library` that has any deps to the proto library. Am I missing something?

I think it is fine to remove protobuf dependency. gRPC dependence was introduced recently which supersedes the protobuf.

**Comment by maxgolov** [comment]
> I think it is fine to remove protobuf dependency.

For CMake we still require protobuf, since its package (both Debian package and vcpkg package) includes the `protoc` .. We also require at least `protobuf3` .. Actually for older Ubuntu-14.xx that comes with `protobuf2` we deploy `protoc` by downloading it from https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-linux-x86_64.zip

While unrelated to Bazel PR, I am not sure if (how) we can safely eliminate dependency on protobuf from CMake build at the moment. Can't comment on Bazel specifics.

**Comment by jsuereth** [comment]
FYI - https://github.com/grpc/grpc/pull/24953

I tried to bump gRPC locally and ran into a bazel issue pulling it in on windows.  I don't think this is related to the legacy-bazel CI breakage but it'd be nice to verify if downstream windows can consume this version of gRPC or if we need to open a bug ourselves to "upgrade ASAP" once that fix is in.

**Review by jsuereth — APPROVED** [review]
Thanks for doing the update!

**Comment by lalitb** [comment]
@bogdandrutu  Can you see if the `Bazel tsan` check failure here is related to this PR ?

**Comment by lalitb** [comment]
@bogdandrutu This is failing for gcc4.8. Thanks.
`
ERROR: C:/users/runneradmin/_bazel_runneradmin/cefevaif/external/com_github_grpc_grpc/BUILD:3194:16: undeclared inclusion(s) in rule '@com_github_grpc_grpc//:google_api_upbdefs':

this rule is missing dependency declarations for the following files included by 'com_github_grpc_grpc/src/core/ext/upbdefs-generated/google/protobuf/descriptor.upbdefs.c':
  'bazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/google/protobuf/descriptor.upbdefs.h'
`

**Comment by lalitb** [comment]
@bogdandrutu . There are some failures for bazel on Windows and gcc4.8. Thanks.

`
ERROR: C:/users/runneradmin/_bazel_runneradmin/cefevaif/external/com_github_grpc_grpc/BUILD:3194:16: undeclared inclusion(s) in rule '@com_github_grpc_grpc//:google_api_upbdefs':

this rule is missing dependency declarations for the following files included by 'com_github_grpc_grpc/src/core/ext/upbdefs-generated/google/protobuf/descriptor.upbdefs.c':
  'bazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/google/protobuf/descriptor.upbdefs.h'
`

**Comment by lalitb** [comment]
closing this, as we have a similar gRPC upgrade PR #666

**Pull request closed without merging**
