### PR TITLE
Add compare operators to nostd::string_view

### PR DESCRIPTION
**Pull request by maxgolov**
This change adds missing methods that exist on standard std::string_view , allowing to use nostd::string_view as key in std::map and other containers.

### CODE REVIEW

**Comment by maxgolov** [comment]
> Please also api/test/nostd/string_view_test.cc

Yes, I will add the tests.

**Comment by kmanghat** [comment]
Could we also add hash functions for nostd::string_view that make it usable with unordered_map and unordered_set? I can do this in a separate PR or it could be added in this one.

**Comment by maxgolov** [comment]
> Could we also add hash functions for nostd::string_view

Are these part of standard std::string_view ? I'd like to ensure that our implementations of nostd classes are as close to standard library as possible. Why? Because that keeps an option on a table to substitute one for another in a neat way. I was planning to submit a separate PR that validates our nostd classes behavior side-by-side with Standard Library, C++17, C++20, as well as gsl::span. Abseil is another good candidate. Comparing just the bare minimum of classes we implement, and the methods we use in SDK.

**Comment by maxgolov** [comment]
Do you mean something like ```nostd::hash<nostd::string_view>``` compatible  with [std::hash](https://en.cppreference.com/w/cpp/string/basic_string_view/hash) ?

**Comment by kmanghat** [comment]
Yeah it looks like it is available in c++ 20, yeah I was thinking of something like that. You could also modify std::hash that way you don't have to do something like this std::unordered_set<nostd::string_view, nostd::MyHash> set

**Pull request merged**
