### PR TITLE
Update meter.h

### PR DESCRIPTION
**Pull request by sanjaypujare**
Fix typo: replace Counter with Gauge (most likely a copy-paste error)

Fixes # (issue)

## Changes

Fix typo: replace Counter with Gauge (most likely a copy-paste error)

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by sanjaypujare** [comment]
CC @lalitb

**Review by lalitb — APPROVED** [review]
LGTM. Thanks.

**Review by owent — APPROVED** [review]
LGTM and thanks.

**Review by marcalff — APPROVED** [review]
LGTM. Thanks for the fix.

**Pull request merged**
