### PR TITLE
Make macros.h available for all source files via version.h

### PR DESCRIPTION
**Pull request by ThomsonTan**
## Changes

As the macros defined in `macros.h` is general for all sources, including it in `version.h` to make it available for all sources (no need for separate `#include "opentelemetry/common/macros.h"` statement.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by marcalff — COMMENTED** [review]
Making this change will expose:

- the `cstdint` header file
- the `regex` headerfile
- the `HAVE_WORKING_REGEX` symbol, which is not using an `OPENTELEMETRY_` prefix and therefore pollutes the build

for any user of any api header file.

I would prefer to apply the include-what-you-use principles, and only include macro.h in the few places where it is needed.

The API header files are stable by now, so there is no real maintenance burden and breaks caused by missing includes on macro.h

What is the motivation or rationale for this change ?

**Comment by ThomsonTan** [comment]
> Making this change will expose:
> 
> * the `cstdint` header file
> * the `regex` headerfile
> * the `HAVE_WORKING_REGEX` symbol, which is not using an `OPENTELEMETRY_` prefix and therefore pollutes the build
> 
> for any user of any api header file.
> 
> I would prefer to apply the include-what-you-use principles, and only include macro.h in the few places where it is needed.
> 
> The API header files are stable by now, so there is no real maintenance burden and breaks caused by missing includes on macro.h
> 
> What is the motivation or rationale for this change ?

Perhaps we should remove cstdint from macro here? `HAVE_WORKING_REGEX` is like any definition in `config.h` which is fine and convenient to be included for every source file under the repo?

The intention was the make the all the generic macros in a common header file for all source files. I am adding some declspec macro for building DLL, so I'd like to avoid including it for every header (there could be many of them).

**Comment by ThomsonTan** [comment]
Perhaps move `#include <regex>` to the source file which need it instead of putting into this generic header file?

**Review by owent — APPROVED** [review]
LGTM

**Review by marcalff — APPROVED** [review]
LGTM with the following changes, please consider to:

- rename HAVE_WORKING_REGEX to OPENTELEMETRY_HAVE_WORKING_REGEX, everywhere (including in the SDK)
- only set OPENTELEMETRY_HAVE_WORKING_REGEX based on the GCC version, but do not include regex.h when setting the flag
- include (conditionally) regex.h when using the flag
- remove the code duplication from trace_state.h

With this, all uses should look like:

```
#if OPENTELEMETRY_HAVE_WORKING_REGEX
#  include <regex>
#endif
```

I know this is an existing issue, but cleaning it up before exposing macro.h is needed, to avoid causing side effects on user code.

No strong opinion on whether to put the code to set  OPENTELEMETRY_HAVE_WORKING_REGEX in macro.h or config.h

Thanks for the fix.

**Comment by marcalff** [comment]
> Perhaps move `#include <regex>` to the source file which need it instead of putting into this generic header file?

Good idea, see my latest review comments.

**Pull request merged**
