### PR TITLE
Upgrade to gRPC 1.46.3 (#1459)

### LINKED ISSUE #1459: [Dependencies] Upgrade to gRPC version 1.46.3
gRPC will require C++14 starting with release 1.47, see the announcement in 1.46:

https://github.com/grpc/grpc/releases/tag/v1.46.0

Upgrade opentelemetry-cpp to the latest gRPC C++ 11 release available, 1.46.3.

This is a required intermediary upgrade step, while awaiting for a decision on if/how to support:
-  C++ 11 gRPC 1.46.3
- C++ 14 gRPC 1.47+
concurrently in the opentelemetry-cpp code base.

### PR DESCRIPTION
**Pull request by marcalff**
Fixes #1459 

## Changes

Upgrade to gRPC 1.46.3

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by lalitb** [comment]
> The gcc error message is not printed, making this hard to investigate.

Looks like if the error data is larger than 1mb, bazel doesn't print it to stderr :
``
stderr (/home/runner/.cache/bazel/e6b8d6759295e14b76bc8cb98b604748/execroot/io_opentelemetry_cpp/bazel-out/_tmp/actions/stderr-2073) exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
``
It does print the filename containing the error message. Probably running locally, and error from file gives more information ?

**Comment by marcalff** [comment]
Hi @lalitb 

I never used Bazel before, so I am really struggling with it.

On a local build on a linux machine, I get:

malff@localhost.localdomain:opentelemetry-cpp> bazel build //...
ERROR: /home/malff/CODE/MARC_GITHUB/opentelemetry-cpp/exporters/jaeger/BUILD:111:11: @bazel_tools//platforms:osx is not a valid configuration key for //exporters/jaeger:jaeger_thrift_gencpp
ERROR: Analysis of target '//exporters/jaeger:jaeger_thrift_gencpp' failed; build aborted: @bazel_tools//platforms:osx is not a valid configuration key for //exporters/jaeger:jaeger_thrift_gencpp
INFO: Elapsed time: 0.035s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

which seems even worse.

**Comment by lalitb** [comment]
> Hi @lalitb
> 
> I never used Bazel before, so I am really struggling with it.
> 
> On a local build on a linux machine, I get:
> 
> ```
> malff@localhost.localdomain:opentelemetry-cpp> bazel build //...
> ERROR: /home/malff/CODE/MARC_GITHUB/opentelemetry-cpp/exporters/jaeger/BUILD:111:11: @bazel_tools//platforms:osx is not a valid configuration key for //exporters/jaeger:jaeger_thrift_gencpp
> ERROR: Analysis of target '//exporters/jaeger:jaeger_thrift_gencpp' failed; build aborted: @bazel_tools//platforms:osx is not a valid configuration key for //exporters/jaeger:jaeger_thrift_gencpp
> INFO: Elapsed time: 0.035s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
> ```
> 
> which seems even worse.

Sorry I missed this message. Will have a look to bazel build.

**Comment by owent** [comment]
BTW: Why don't we upgrade gRPC to the latest version of gRPC(v1.48.0)?

**Comment by lalitb** [comment]
> BTW: Why don't we upgrade gRPC to the latest version of gRPC(v1.48.0)?

Yes. we can try upgrading to gRPC v1.48.0, and/or bazel v4.2.2. Saw somewhere that the `segmentation fault: 11` we are observing in MacOS is fixed in the latest version of bazel.

**Comment by lalitb** [comment]
> > BTW: Why don't we upgrade gRPC to the latest version of gRPC(v1.48.0)?
> 
> Yes. we can try upgrading to gRPC v1.48.0, and/or bazel v4.2.2. Saw somewhere that the `segmentation fault: 11` we are observing in MacOS is fixed in the latest version of bazel.

Ok, I realize it won't be straightforward to upgrade to 1.48.0, as it needs C++14 to build as discussed here - https://github.com/open-telemetry/opentelemetry-cpp/discussions/1449.

**Comment by marcalff** [comment]
Change superseded by PR #1608

Abandoning this branch.

**Pull request closed without merging**
