### PR TITLE
Add option WITH_BENCHMARK to disable building benchmarks

### PR DESCRIPTION
**Pull request by ThomsonTan**
## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by marcalff — APPROVED** [review]
LGTM, and good idea.

**Comment by lalitb** [comment]
Thanks, can we also add the "benchmark" tag for Bazel, it will allow to disable building  benchmark test for bazel too.

refer - https://github.com/open-telemetry/opentelemetry-cpp/blob/6644ddd7f3b75a7bfd3855946e780de26e95b534/api/test/trace/BUILD#L8

**Review by lalitb — CHANGES_REQUESTED** [review]
Requesting similar changes for bazel as mentioned in comments :)

**Comment by ThomsonTan** [comment]
> Requesting similar changes for bazel as mentioned in comments :)

Done the change.

**Review by lalitb — APPROVED** [review]
Thanks. Much needed change :)

**Pull request merged**
