### PR TITLE
Fix leak in Jaeger exporter

### PR DESCRIPTION
**Pull request by bjosv**
During our introduction of Jaeger and using the `JaegerExporter` we found this memory leak.
There is currently no unittest for the `JaegerExporter` in opentelemetry-cpp that could have caught this, but maybe we should add something similar to the ongoing `ZipkinExporter` test (#1155)?

## Changes

The jaeger_span was never destroyed after its release from the JaegerRecordable.
This change let a `std::unique_ptr` handle the destruction when going out of scope, first allowing the`thrift::Span` to be copied to the `span_buffer_`.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by lalitb — APPROVED** [review]
LGTM. Thanks for the fix. 
Agree, Jaeger exporter tests need to be improved.

**Review by esigo — APPROVED** [review]
thanks for the fix.
LGTM.
I will add more tests without mock to cover `Thrift` part.

**Comment by bjosv** [comment]
> I will add more tests without mock to cover `Thrift` part.
Great! Was thinking of looking into this, but just let me know If I can be of any help.

**Comment by esigo** [comment]
We can catch the leak in the new [test](https://github.com/open-telemetry/opentelemetry-cpp/runs/4607890718?check_suite_focus=true#step:5:222).

**Comment by lalitb** [comment]
@bjosv  - can you update the branch to main, to allow this to be merged.

**Comment by bjosv** [comment]
@lalitb  The PR has now been updated to the latest from main.

**Comment by bjosv** [comment]
CI step `Bazel on MacOS` failed with
`ERROR: Analysis of target '//exporters/elasticsearch:es_log_exporter_test' failed; build aborted: Analysis of target '@local_config_cc//:tvos_x86_64' failed`

It doesn't seem to be related to my correction according to the output, but I'm not familiar with the test.

**Comment by ThomsonTan** [comment]
Thanks for catching and fixing.

**Pull request merged**
