### PR TITLE
[SDK] Add base2 exponential histogram indexer

### PR DESCRIPTION
**Pull request by euroelessar**
Updates #1391 

## Changes

Add Base2ExponentialHistogramIndexer for calculating index for a given value and scale.
It will be used in base2 exponential histogram in followup changes.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [x] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by marcalff — APPROVED** [review]
LGTM, and well done.

**Review by esigo — APPROVED** [review]
LGTM
Thanks :)

**Review by lalitb — APPROVED** [review]
LGTM. Thanks

**Comment by dufferzafar** [comment]
Is there a timeline/plan as to when the exponential histogram would be in usable shape?

@euroelessar Could you please specify the next steps one would need to take to implement this?

I've been going over the code and would like to take a stab at it.

**Pull request merged**
