### PR TITLE
Remove warnings of protobuf

### PR DESCRIPTION
**Pull request by owt5008137**
Related to #249 

## Changes

Remove warnings of protobuf. There is no functional change.

For significant contributions please make sure you have completed the following items:

* [x] `CHANGELOG.md` updated for non-trivial changes
* [x] Unit tests have been added
* [x] Changes in public API reviewed

### CODE REVIEW

**Review by lalitb — APPROVED** [review]
Thanks for the fix :)

**Review by maxgolov — APPROVED** [review]

**Comment by maxgolov** [comment]
Thank you!

**Comment by lalitb** [comment]
@owt5008137 Can you rebase the branch with main, that will allow us to merge the changes.

**Comment by owt5008137** [comment]
> @owt5008137 Can you rebase the branch with main, that will allow us to merge the changes.

done

**Comment by lalitb** [comment]
Not sure why the CLA verification is stuck for this PR, while it is passing for others.

**Comment by owt5008137** [comment]
> 
> 
> Not sure why the CLA verification is stuck for this PR, while it is passing for others.

Don't know the reason either, but it seems passed after I click the **Update** button.

**Pull request merged**
