### PR TITLE
Add noexcept/const qualifier at missing places for Trace API.

### PR DESCRIPTION
**Pull request by lalitb**
## Changes

This allows these methods to be used in the functions which are noexcept without explicit exception handling.

We may have to look at similar changes for log/metrics api separately.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by ThomsonTan** [comment]
Just curious whether adding noexcept could break existing API usage in any case.

**Comment by lalitb** [comment]
> Just curious whether adding noexcept could break existing API usage in any case.

I don't think it should break API/ABI compatibility. Though reverse ( removing noexcept) can break things.

**Comment by reyang** [comment]
> > Just curious whether adding noexcept could break existing API usage in any case.
> 
> I don't think it should break API/ABI compatibility. Though reverse ( removing noexcept) can break things.

IIRC noexcept is not included in the mangled name but not sure if it's compiler specific or covered by the standard spec. From semantic standpoint +1 with what @lalitb said.

**Review by reyang — APPROVED** [review]

**Comment by lalitb** [comment]
> IIRC noexcept is not included in the mangled name but not sure if it's compiler specific or covered by the standard spec.

Validated it across gcc, clang and msvc and it generates the same mangled name for both these prototypes:
```cpp
void foo1()
void foo2() noexcept
```
msvc: https://gcc.godbolt.org/z/sb7szM8xd
gcc: https://gcc.godbolt.org/z/17fovvd37
clang: https://gcc.godbolt.org/z/Pebcox9xz

**Review by ThomsonTan — APPROVED** [review]

**Pull request merged**
