### PR TITLE
Migrate from @bazel_tools//platforms to https://github.com/bazelbuild/platforms

### PR DESCRIPTION
**Pull request by davidmandle**
## Changes

This MR migrates [platforms](https://bazel.build/extending/platforms) constraints from the deprecated `@bazel_tools//platforms` target to instead depend on the `https://github.com/bazelbuild/platforms` repository, per https://github.com/bazelbuild/bazel/issues/8622

This enables compatibility with the newly released [Bazel 6.0.0](https://github.com/bazelbuild/bazel/releases).

### CODE REVIEW

**Comment by davidmandle** [comment]
> Could this break some older version of bazel?

I don't know for sure, but I do know that it continues to build successfully with the Bazel version specified in `.bazelversion` (4.2.0), and that other large projects have already successfully undergone this migration (e.g. `grpc`: https://github.com/grpc/grpc/pull/29842).

**Comment by davidmandle** [comment]
Let me know if there's any actions I can take to address concerns about Bazel backwards compatibility. For what its worth, the `grpc` library, which has undergone this migration, tests over its set of [supported Bazel versions ](https://github.com/grpc/grpc/blob/99a7f2995e66f9d6f5c3403dc7178238251fb2b5/bazel/supported_versions.txt).

**Comment by lalitb** [comment]
I don’t see any issue if this migration enable supporting bazel v6.0.0, is also working with v4.2.0. As of now we haven’t documented minimal supported bazel version - perhaps we can start doing that once we bump up bazel version to 6.0.0. 

Also not related to this PR, but we need to think about continuing g++4.8 support, as that support is restricted with lower version of gRPC and bazel. 

Approving this, but need one more approval to merge, and most of the approvers/maintainers are not active during holiday season. Thanks for the PR.

**Review by lalitb — APPROVED** [review]

**Review by owent — APPROVED** [review]
LGTM

**Review by owent — CHANGES_REQUESTED** [review]
It seems also need upgrade gtest to 1.11.0 or upper and upgrade gRPC to 1.49.0 or upper.
Or the dependencies still use `@bazel_tools//platforms`, which can not compile with latest bazel.

**Comment by lalitb** [comment]
> It seems also need upgrade gtest to 1.11.0 or upper and upgrade gRPC to 1.49.0 or upper.

Oh didn't realize that. Thanks for pointing out. Is it better to upgrade gRPC now, or once we bump the bazel version?

**Comment by davidmandle** [comment]
Thanks @owent, I've upgraded gtest to 1.12.1 and gRPC to 1.49.2. Let me know if there's any other actions I should take.

**Comment by lalitb** [comment]
> Thanks @owent, I've upgraded gtest to 1.12.1 and gRPC to 1.49.2. Let me know if there's any other actions I should take.

CMake is still using older versions of these libraries, and also [third_part_releases](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/third_party_release) file should have these updated versions.

**Review by owent — APPROVED** [review]
LGTM now.And the gRPC version in [ci/setup_grpc.sh](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/ci/setup_grpc.sh) and [ci/do_ci.sh](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/ci/do_ci.sh) can also be updated.

**Comment by davidmandle** [comment]
Thanks. I believe now I've updated the versions throughout.

**Pull request merged**
