### PR TITLE
[RELEASE] Prepare release 1.9.1

### LINKED ISSUE #2148: [RELEASE] Prepare release 1.9.1
Publish release 1.9.1

### PR DESCRIPTION
**Pull request by marcalff**
Fixes #2148

## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [X] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by owent — COMMENTED** [review]
should we also update version.h?

**Review by owent — COMMENTED** [review]
Do we also need update version.h?

**Review by owent — APPROVED** [review]

**Comment by marcalff** [comment]
@owent 

> Do we also need update version.h?

Both files:

./api/include/opentelemetry/version.h
./sdk/include/opentelemetry/sdk/version/version.h

are updated.

**Review by esigo — APPROVED** [review]
LGTM
Thanks :)

**Comment by owent** [comment]
> @owent
> 
> > Do we also need update version.h?
> 
> Both files:
> 
> ./api/include/opentelemetry/version.h ./sdk/include/opentelemetry/sdk/version/version.h
> 
> are updated.

Thanks, maybe there is some wrong with my network, I find only one changed file when first open this PR, and there is no problem now.

**Review by lalitb — APPROVED** [review]

**Comment by marcalff** [comment]
Release on hold, waiting for:

* https://github.com/open-telemetry/opentelemetry-cpp/issues/2153

to avoid breaking the build for applications with 1.9.1

**Review by ThomsonTan — APPROVED** [review]

**Pull request merged**
