### PR TITLE
Add SpanId benchmark.

### PR DESCRIPTION
**Pull request by g-easy**

### CODE REVIEW

**Comment by rnburn** [comment]
Could we execute the benchmarks as part of the CI and upload the results as artifacts? 

I've found it makes it much easier to share and compare results as they change. 

[Here's](https://circleci.com/gh/lightstep/lightstep-tracer-cpp/7232#artifacts/containers/0) an example of the benchmarking artifacts we upload for the lightstep benchmarks (includes [times](https://7232-57146219-gh.circle-artifacts.com/0/benchmark/span_operations_benchmark_result.txt) and the [profiles](https://7232-57146219-gh.circle-artifacts.com/0/benchmark/span_operations_benchmark-BM_SpanLog2-stream.svg))

**Comment by g-easy** [comment]
That sounds great! How reliable/accurate are the timings on CI?

**Comment by rnburn** [comment]
They can vary somewhat but I've still found them accurate enough to be useful.

**Comment by g-easy** [comment]
Should I add a new `do_ci` target or use an existing one?

I should use something like https://github.com/lightstep/lightstep-tracer-cpp/blob/bd84e3aa997a5d9af589c40bd208f1dda252501a/bazel/lightstep_build_system.bzl#L193 ?

**Comment by rnburn** [comment]
> Should I add a new do_ci target or use an existing one?

I'd recommend a new ci target. The benchmarks can take a while to run and they use different compilation options.

I went ahead and approved if you'd rather not tie up this PR with benchmarking CI.

**Comment by rnburn** [comment]
> I should use something like https://github.com/lightstep/lightstep-tracer-cpp/blob/bd84e3aa997a5d9af589c40bd208f1dda252501a/bazel/lightstep_build_system.bzl#L193 ?

With lightstep tracer, I had the benchmarking results as targets in bazel, but there might be a better way to set this up. 

Maybe we could make them runnable targets, then produce the results by doing a `bazel query` and running each target -- what do you think?

**Comment by g-easy** [comment]
> approved

Thanks. I would prefer to merge this now and follow up with the CI stuff.

> new ci target

Agreed.

> benchmarking results as targets in bazel

I like your approach. I was also considering `bazel query` or maybe use tags.

**Comment by g-easy** [comment]
#34 for CI.

**Pull request merged**
