### PR TITLE
[exporters/prometheus] Remove explicit timestamps from metric points

### LINKED ISSUE #2316: Prometheus exporter should not set explicit timestamps
**Steps to reproduce**

I saw second-hand that the prometheus exporter adds explicit timestamps, but don't have exact reproduction steps.

```
# TYPE grpc_client_attempt_started_ counter
grpc_client_attempt_started_{grpc_method="grpc.testing.TestService/UnaryCall",grpc_target="dns:///10.52.1.55:14285"} 10 1694819876572
```

The last number on the right is the start timestamp.

**What is the expected behavior?**
Metrics should not have explicit timestamps set. From the [OpenMetrics specification](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#metric)

> MetricPoints SHOULD NOT have explicit timestamps.

**What is the actual behavior?**

Explicit timestamps are added to prometheus metrics.

https://github.com/open-telemetry/opentelemetry-cpp/blob/0563a71ce3ea2c580f535996aeb8ce9246f2d703/exporters/prometheus/src/exporter_utils.cc#L265

**Additional context**

In prometheus, the scrape time is used as the timestamp.  Explicit timestamps can limit some functionality, such as compatibility with the [prometheus push gateway](https://github.com/prometheus/pushgateway#about-timestamps), so they are generally not recommended.

### PR DESCRIPTION
**Pull request by punya**
Fixes #2316

## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

*   [x] `CHANGELOG.md` updated for non-trivial changes
*    [x]  Unit tests have been added
*   [x] Changes in public API reviewed

### CODE REVIEW

**Comment by marcalff** [comment]
@punya Thanks for the fix.

The failing CI is due to:

```
/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/prometheus/src/exporter_utils.cc:47:12: error: unused variable 'time' [-Werror,-Wunused-variable]
      auto time          = metric_data.end_ts.time_since_epoch();

```

**Review by lalitb — APPROVED** [review]
LGTM once the CI is fixed.

**Comment by lalitb** [comment]
Format needs to be fixed, either by running cmake-format, or adding the patch below:

```cpp
--- a/exporters/prometheus/test/exporter_utils_test.cc
+++ b/exporters/prometheus/test/exporter_utils_test.cc
@@ -43,7 +43,8 @@ void assert_basic(prometheus_client::MetricFamily &metric,
   ASSERT_EQ(metric.type, type);                      // type translated
 
   // Prometheus metric data points should not have explicit timestamps
-  for (const prometheus::ClientMetric &cm : metric.metric) {
+  for (const prometheus::ClientMetric &cm : metric.metric)
+  {
     ASSERT_EQ(cm.timestamp_ms, 0);
   }
```

**Review by marcalff — APPROVED** [review]
Thanks for the fix.

**Pull request merged**
