### PR TITLE
[EXPORTER] Elastic Search exporter follow ECS guidelines

### LINKED ISSUE #3091: ElasticSearch Exporter does not follow ECS guidelines and logging reference
**Describe your environment** 

Version 1.17.0 of this project.

**Steps to reproduce**
Use the `ElasticsearchLogRecordExporter`

**What is the expected behavior?**
The json sent should follow the [ECS guidelines](https://www.elastic.co/guide/en/ecs/current/ecs-guidelines.html) as much as possible as well as the [ECS logging reference](https://www.elastic.co/guide/en/ecs-logging/overview/current/intro.html#_default_fields)

**What is the actual behavior?**
Some basic field needed by ELK are not there like `@timestamp` (`timestamp` today in the code)

```
General guidelines
The document MUST have the @timestamp field.
Use the [data types](https://www.elastic.co/guide/en/elasticsearch/reference/8.15/mapping-types.html) defined for an ECS field.
Use the ecs.version field to define which version of ECS is used.
Map as many fields as possible to ECS.
```

All attributes/resources are set under the `attributes`/`resources` key while I think they should be set at the root of the json or at least give a possibility to set attributes/resources at the root of the object so we can fill some fields like [user.id](https://www.elastic.co/guide/en/ecs/8.11/ecs-user.html#field-user-id)

### PR DESCRIPTION
**Pull request by ShadowMaxLeb**
Fixes #3091 

## Changes

Try to follow as much as possible the [ECS guidelines](https://www.elastic.co/guide/en/ecs/current/ecs-guidelines.html) and the [ECS Logs reference](https://www.elastic.co/guide/en/ecs/8.11/ecs-log.html)

This impacts fields:
* timestamp: now set to @timestamp with a `Date` string
* body: now set to `message`
* name: now set to `log.logger`
* severity: now set to `log.level`
* attributes: not under the `attributes` key anymore

### CODE REVIEW

**Review by marcalff — APPROVED** [review]
LGTM, thanks for the fix.

**Comment by marcalff** [comment]
Thanks for the fix.

@ShadowMaxLeb Please merge main into this PR, to resolve "This branch is out-of-date with the base branch".

**Review by lalitb — APPROVED** [review]

**Comment by MaxLeb** [comment]
> Thanks for the fix.
> 
> @ShadowMaxLeb Please merge main into this PR, to resolve "This branch is out-of-date with the base branch".
> 

I will try to update it next week as I cannot do it right now.

**Comment by ShadowMaxLeb** [comment]
@marcalff , How can I retry the failed job as it failed because it was lacking a runner ?

**Pull request merged**
