### PR TITLE
Fix build warnings about missing aggregates

### PR DESCRIPTION
**Pull request by taekahn**
Fixes # (issue)

## Changes

Fixing a build warning about missing initialize for aggregate initialization.

### CODE REVIEW

**Comment by taekahn** [comment]
> @taekahn thanks for the fix. Could you please help fix the CLA issue?

I'm not sure what i have to do. I clicked on the link in the bot message and signed the form 3 times.

**Comment by lalitb** [comment]
@taekahn  Can you sign up for EasyCLA so that we can merge the PR ?

**Comment by taekahn** [comment]
> @taekahn Can you sign up for EasyCLA so that we can merge the PR ?

As i said above, i clicked on the link. Registered. Signed the form several times. 
Not sure what i need to do here.

**Comment by marcalff** [comment]
The commit is:

Jeffrey Reynolds authored and [taekahn](https://github.com/open-telemetry/opentelemetry-cpp/commits?author=taekahn) committed on May 18

It could be that the missing CLA and id is about Jeffrey, not taekahn.

**Review by lalitb — APPROVED** [review]

**Pull request merged**
