### PR TITLE
Increase the default size of FD_SETSIZE

### LINKED ISSUE #1476: The default value of FD_SETSIZE is too small for real scenario
**Describe your environment**
Windows 11 10.0.22000.739

**Steps to reproduce**
Run curl_http_test.exe

**What is the expected behavior?**
The test should pass

**What is the actual behavior?**
The test failed

**Additional context**
The test is failed on that the allocated socket handle value is larger than `FD_SETSIZE` which is 64. The value seems too small for real scenario.

### PR DESCRIPTION
**Pull request by ThomsonTan**
Fixes #1476.

## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by lalitb** [comment]
Just wondering if the issue would be still valid once @owent async changes are merged, as that PR removes `select` call usage. Also, there was similar fix done for Linux - #1410 to replace `select` call with `poll`. If there is similar alternative for Windows ?

**Comment by ThomsonTan** [comment]
> Just wondering if the issue would be still valid once @owent async changes are merged, as that PR removes `select` call usage. Also, there was similar fix done for Linux - #1410 to replace `select` call with `poll`. If there is similar alternative for Windows ?

@lalitb thanks for the reminder. Yes, the async change will remove current code with issue, so I think I could close this PR once the async change is merged. Also I think #1410 applies to Windows as well, right?

**Comment by lalitb** [comment]
> Also I think https://github.com/open-telemetry/opentelemetry-cpp/pull/1410 applies to Windows as well, right?

#1410 replaces `select` with `poll` only for POSIX and keeps `select` for Windows. Merging this PR will add more conflict with async PR. If this is not the blocker, we can let @owent to decide how to procced with this PR?

**Comment by ThomsonTan** [comment]
Ok. I'll just leave this PR open and will close it once the async change from @owent gets merged, no need for merging.

**Comment by owent** [comment]
libcurl use `select` on WIndows and `poll` on Linux, just like #1410 . According to https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-select, nfds of `select` on Windows is just ignored. I think we can wait for #1413 to be merged.

**Pull request closed without merging**
