### PR TITLE
[CI] Upgrade abseil-cpp version from 20220623.1 to 20230125.2

### PR DESCRIPTION
**Pull request by cngzhnp**
Fixes # (issue)

## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by marcalff** [comment]
@cngzhnp 

Thanks for the PR.

The upgrade of abseil itself looks ok.

This PR needs some coordination with the deprecation of C++11 (PR and date to be announced), to make sure the transition to C++14 and upgrade of dependencies are clean.

**Comment by CoderPoet** [comment]
If this PR is not merged, will there be incompatibilities when opentelemetry-cpp is used with the new version of absl?

**Comment by CoderPoet** [comment]
> If this PR is not merged, will there be incompatibilities when opentelemetry-cpp is used with the new version of absl?

An issue with version conflicts was encountered：https://github.com/open-telemetry/opentelemetry-cpp/issues/2238

**Comment by marcalff** [comment]
This PR is no longer needed, as PR #2163 already upgraded abseil-cpp to version 20230125.3

Closing.

**Pull request closed without merging**
