### PR TITLE
Integrate CPack for binary package

### LINKED ISSUE #1834: Integrate `CPack` for binary package
**Is your feature request related to a problem?**
We need a binary distribution package.

**Describe the solution you'd like**
Integarate [CPack](https://cmake.org/cmake/help/latest/module/CPack.html) in the CMake build system.

### PR DESCRIPTION
**Pull request by flier**
Fixes #1834

## Changes

Please provide a brief description of the changes here.

- Integrate `CPack` in the CMake build system
- Generate binary package with `make package` or `ninja package`

For significant contributions please make sure you have completed the following items:

* [x] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by lalitb** [comment]
@flier  - Would it be fine if we track the fix through #1662. I can plan to have it ready for next week release, as there have been multiple asks for it ?

**Review by owent — APPROVED** [review]
LGTM

**Comment by flier** [comment]
@owent

**Review by esigo — CHANGES_REQUESTED** [review]
Blocked per https://github.com/open-telemetry/opentelemetry-cpp/pull/1835#issuecomment-1334814529

**Comment by lalitb** [comment]
closing this for #1662

**Pull request closed without merging**
